"""Real gym exposing the operator's own current portfolio state -- local git
repos on this machine and this GitHub account's own repos -- as a queryable
`Environment`. Every capability here is `Consequence.READ` -- this gym never
actuates anything; it only answers questions against real, live data.
`requires_authority` defaults `False`: reading your own local filesystem and
your own already-authenticated `gh` session carries no consequence to gate.

GENERATED by ggen from ggen/chatman-state-pack/ontology.ttl -- do not
hand-edit. The capability catalog (iri/title/binding, in
cs:capabilityOrder) is echoed from that ontology's cs:GymCapability
individuals; the actual live data-fetching logic lives in
gymact.gyms.chatman_state (hand-written I/O boundary, never generated --
same split cloud_topology.py established for provider-published cloud
data).
"""

from __future__ import annotations

from dataclasses import asdict
from pathlib import Path
from typing import Any
from uuid import uuid4

from gymact.models import Capability, Consequence

from .chatman_state import (
    count_github_repos,
    count_local_repos,
    discover_github_repos,
    discover_local_repos,
    estimated_effort_cost,
)

CHATMAN_STATE_CAPABILITIES: tuple[Capability, ...] = (
    Capability(
        iri="urn:gymact:chatman-state:capability:list_local_repos",
        title="List the most recently active real local git repos under $HOME, capped and recency-sorted, with the real total found also disclosed (payload: {})",
        consequence=Consequence.READ,
        binding="list_local_repos",
    ),
    Capability(
        iri="urn:gymact:chatman-state:capability:list_github_repos",
        title="List the most recently pushed real repos on this GitHub account via a live gh CLI call, capped and recency-sorted, with the real total found also disclosed (payload: {})",
        consequence=Consequence.READ,
        binding="list_github_repos",
    ),
    Capability(
        iri="urn:gymact:chatman-state:capability:estimated_effort_cost",
        title="Real engineering_hour cost estimate for one named local repo over a real git log window, via a named, disclosed heuristic -- never a claim of measured wall-clock time (payload: {'repo': str, 'since': str?})",
        consequence=Consequence.READ,
        binding="estimated_effort_cost",
    ),
    Capability(
        iri="urn:gymact:chatman-state:capability:portfolio_summary",
        title="Real local + GitHub repo counts found vs. returned -- the disclosed cap-vs-total honesty check for the other two list capabilities (payload: {})",
        consequence=Consequence.READ,
        binding="portfolio_summary",
    ),
)
_CAPABILITY_BY_BINDING = {c.binding: c for c in CHATMAN_STATE_CAPABILITIES}


class ChatmanStateEnvironment:
    """A materialized, real, live snapshot of local + GitHub portfolio state."""

    def __init__(self, *, requires_authority: bool = False, repo_limit: int = 25) -> None:
        self.environment_id = f"urn:gymact:chatman-state:environment:{uuid4().hex}"
        self.requires_authority = requires_authority
        self.repo_limit = repo_limit
        self._closed = False

    def _ensure_open(self) -> None:
        if self._closed:
            raise RuntimeError("environment is torn down")

    def capabilities(self) -> tuple[Capability, ...]:
        self._ensure_open()
        return CHATMAN_STATE_CAPABILITIES

    def _state(self) -> dict[str, Any]:
        return {"repo_limit": self.repo_limit}

    async def observe(self) -> dict[str, Any]:
        self._ensure_open()
        return self._state()

    async def actuate(self, capability: Capability, payload: dict[str, Any]) -> dict[str, Any]:
        self._ensure_open()
        before = self._state()
        binding = capability.binding
        if binding == "list_local_repos":
            repos = discover_local_repos(limit=self.repo_limit)
            result: Any = [asdict(r) for r in repos]
        elif binding == "list_github_repos":
            repos = discover_github_repos(limit=self.repo_limit)
            result = [asdict(r) for r in repos]
        elif binding == "estimated_effort_cost":
            repo = payload.get("repo")
            if not isinstance(repo, str) or not repo:
                raise ValueError("payload.repo must be a non-empty string")
            since = payload.get("since", "7 days ago")
            if not isinstance(since, str) or not since:
                raise ValueError("payload.since must be a non-empty string when provided")
            cost = estimated_effort_cost(Path(repo), since=since)
            result = cost.model_dump()
        elif binding == "portfolio_summary":
            result = {
                "local_repo_count_found": count_local_repos(),
                "local_repo_count_returned": min(self.repo_limit, count_local_repos()),
                "github_repo_count_found": count_github_repos(),
                "github_repo_count_returned": min(self.repo_limit, count_github_repos()),
            }
        else:
            raise ValueError(f"unsupported chatman-state binding: {binding}")
        return {
            "before": before,
            "after": self._state(),
            "capability": capability.iri,
            "result": result,
        }

    async def verify(self, expected: dict[str, Any]) -> tuple[bool, dict[str, Any]]:
        self._ensure_open()
        observed = self._state()
        passed = all(observed.get(key) == value for key, value in expected.items())
        return passed, observed

    async def checkpoint(self) -> dict[str, Any]:
        self._ensure_open()
        # Live-loaded, read-only gym -- nothing real to capture beyond the
        # configured repo_limit itself.
        return {"repo_limit": self.repo_limit}

    async def restore(self, checkpoint: dict[str, Any]) -> None:
        self._ensure_open()
        if checkpoint.get("repo_limit") != self.repo_limit:
            raise ValueError("checkpoint belongs to a differently configured environment")

    async def teardown(self) -> None:
        self._closed = True


class ChatmanStateProvider:
    """GymAct `EnvironmentProvider` materializing a real,
    live-loaded `ChatmanStateEnvironment`."""

    name = "chatman-state"
    materialization_requires_authority = False

    async def materialize(
        self, *, scenario: str | None, config: dict[str, Any]
    ) -> ChatmanStateEnvironment:
        requires_authority = config.get("requires_authority", False)
        if not isinstance(requires_authority, bool):
            raise TypeError("config.requires_authority must be a boolean")
        repo_limit = config.get("repo_limit", 25)
        if not isinstance(repo_limit, int) or repo_limit <= 0:
            raise TypeError("config.repo_limit must be a positive int")
        return ChatmanStateEnvironment(
            requires_authority=requires_authority, repo_limit=repo_limit
        )
