"""Real, independent validation that `gymact.gyms.cloud_topology`'s loaded AWS/Azure/GCP data
was modeled correctly -- not merely that it loaded without raising an exception.

GENERATED by ggen from ggen/cloud-topology-validation-pack/ontology.ttl -- do not hand-edit.
Every provider policy fact (loader/recount function names, staleness threshold, the
degenerate-services exception, the spot-check pair) and every static reason-code string below
is echoed verbatim from that ontology, per pack-authoring-pack's "templates echo, they never
synthesize" rule -- to change the policy, edit the ontology and re-run `ggen sync run`, then
`ggen receipt verify` to get a fresh, durable proof that this file matches it.
`.ggen-v2/receipt.json` is that proof: an actor must not also be the judge of its own outcome
(see gymact/verification.py, combinatorial_ocel.py's `validate_ocel_log`), and neither may this
generated file silently drift from the ontology that is supposed to define it.

Per this repo's own, already-established discipline, every check here either:

1. re-derives a real value from the same raw source data via a SEPARATE code path from
   `cloud_topology.py`'s own loaders (never a second call to the function under test), or
2. checks a real structural invariant against the loaded `CloudTopology` object itself that a
   "did it load" check can never catch (e.g. a service wrongly linked to a region that doesn't
   exist in the same topology).

`cloud_topology.py` itself is NOT generated -- it is imperative I/O against botocore / Azure /
GCP's own public sources, not a projection of admitted ontology facts.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path

from .cloud_topology import (
    _AZURE_SNAPSHOT_PATH,
    _GCP_SNAPSHOT_PATH,
    CloudTopology,
    load_aws_topology,
    load_azure_topology,
    load_gcp_topology,
)

__all__ = ["ValidationResult", "validate_all_topologies"]

#: topology.region_codes() contains a duplicate -- len(codes) != len(set(codes)).
#: topology.service_names() contains a duplicate.
#: now - fetched_at exceeds the provider's cv:staleAfterDays.
#: topology.fetched_at is present but datetime.fromisoformat() rejects it.
#: topology.region_codes() is empty for every real provider, always.
#: topology.service_names() is empty AND cv:hasDegenerateServices is false for this provider (gcp is the real, documented exception -- see cv:gcp).

#: Real, disclosed staleness threshold -- a snapshot older than this is flagged, never
#: silently treated as current. (Echoed from cv:staleAfterDays -- every ontology provider
#: that carries one shares this single value; the admission gate does not yet enforce
#: uniqueness, so this picks the real max via `ORDER BY DESC(...) LIMIT 1` rather than
#: concatenating every row.)
_STALENESS_THRESHOLD = timedelta(days=30)

#: Real, documented exception: providers with cv:hasDegenerateServices=true.
_PROVIDERS_WITH_DEGENERATE_SERVICES = frozenset({
    "gcp",
})


@dataclass(frozen=True)
class ValidationResult:
    provider: str
    valid: bool
    problems: tuple[str, ...] = ()
    stale: bool = False
    stale_reasons: tuple[str, ...] = ()
    independent_region_count: int | None = None
    independent_service_count: int | None = None
    loaded_region_count: int = 0
    loaded_service_count: int = 0


def _structural_problems(topology: CloudTopology) -> tuple[str, ...]:
    """Real invariants checked against the loaded topology object alone."""
    problems: list[str] = []

    region_codes = topology.region_codes()
    if len(region_codes) != len(set(region_codes)):
        problems.append("DUPLICATE_REGION_CODE")
    if len(region_codes) == 0:
        problems.append("ZERO_REGIONS")

    service_names = topology.service_names()
    if len(service_names) != len(set(service_names)):
        problems.append("DUPLICATE_SERVICE_NAME")
    if len(service_names) == 0 and topology.provider not in _PROVIDERS_WITH_DEGENERATE_SERVICES:
        problems.append("ZERO_SERVICES")

    region_code_set = set(region_codes)
    for service_name, regions in topology.service_region_availability.items():
        for region in regions:
            if region not in region_code_set:
                problems.append(f"DANGLING_REGION_REFERENCE:{service_name}->{region}")

    for region in topology.regions:
        if region.provider != topology.provider:
            problems.append(f"CROSS_PROVIDER_REGION:{region.code}")
    for svc in topology.services:
        if svc.provider != topology.provider:
            problems.append(f"CROSS_PROVIDER_SERVICE:{svc.name}")

    return tuple(problems)


def _staleness(fetched_at: str | None) -> tuple[bool, tuple[str, ...]]:
    if fetched_at is None:
        return False, ()  # live-loaded providers: no staleness concept
    try:
        fetched = datetime.fromisoformat(fetched_at)
    except ValueError:
        return True, ("UNPARSEABLE_FETCHED_AT",)
    if fetched.tzinfo is None:
        fetched = fetched.replace(tzinfo=timezone.utc)
    age = datetime.now(timezone.utc) - fetched
    if age > _STALENESS_THRESHOLD:
        return True, ("FETCHED_AT_OLDER_THAN_THRESHOLD",)
    return False, ()



def _independent_aws_recount(*, partition: str = "aws") -> tuple[int, int]:
    """Re-derives aws region/service counts directly from `botocore`'s bundled
    `endpoints.json`, via code that does NOT call `load_aws_topology()` -- a separate
    transform, so a bug in that function's own logic cannot hide from this check."""
    from botocore.loaders import create_loader

    data = create_loader().load_data("endpoints")
    real_partition = next(x for x in data["partitions"] if x.get("partition") == partition)
    return len(real_partition.get("regions", {})), len(real_partition.get("services", {}))


def validate_aws() -> ValidationResult:
    topology = load_aws_topology()
    problems = list(_structural_problems(topology))

    independent_regions, independent_services = _independent_aws_recount()
    if independent_regions != len(topology.regions):
        problems.append(
            f"REGION_COUNT_MISMATCH:loaded={len(topology.regions)},independent={independent_regions}"
        )
    if independent_services != len(topology.services):
        problems.append(
            f"SERVICE_COUNT_MISMATCH:loaded={len(topology.services)},independent={independent_services}"
        )
    # Real spot-check: a well-known, long-standing real AWS service must
    # appear in a well-known, long-standing real region.
    if "s3" not in topology.services_in_region("us-east-1"):
        problems.append("SPOT_CHECK_FAILED:s3_not_in_us-east-1")

    stale, stale_reasons = False, ()
    return ValidationResult(
        provider="aws",
        valid=not problems,
        problems=tuple(problems),
        stale=stale,
        stale_reasons=stale_reasons,
        independent_region_count=independent_regions,
        independent_service_count=independent_services,
        loaded_region_count=len(topology.regions),
        loaded_service_count=len(topology.services),
    )



def _independent_azure_recount(path: Path) -> tuple[int, int]:
    """Re-parses the bundled azure snapshot file directly, via code that does NOT
    call `_load_snapshot_topology()`."""
    raw = json.loads(path.read_text())
    return len(raw.get("regions", [])), len(raw.get("service_tags", []))


def validate_azure(*, snapshot_path: Path = _AZURE_SNAPSHOT_PATH) -> ValidationResult:
    topology = load_azure_topology(snapshot_path=snapshot_path)
    problems = list(_structural_problems(topology))

    independent_regions, independent_services = _independent_azure_recount(snapshot_path)
    if independent_regions != len(topology.regions):
        problems.append(
            f"REGION_COUNT_MISMATCH:loaded={len(topology.regions)},independent={independent_regions}"
        )
    if independent_services != len(topology.services):
        problems.append(
            f"SERVICE_COUNT_MISMATCH:loaded={len(topology.services)},independent={independent_services}"
        )

    stale, stale_reasons = _staleness(topology.fetched_at)
    return ValidationResult(
        provider="azure",
        valid=not problems,
        problems=tuple(problems),
        stale=stale,
        stale_reasons=stale_reasons,
        independent_region_count=independent_regions,
        independent_service_count=independent_services,
        loaded_region_count=len(topology.regions),
        loaded_service_count=len(topology.services),
    )



def _independent_gcp_recount(path: Path) -> tuple[int, int]:
    """Re-parses the bundled gcp snapshot file directly, via code that does NOT
    call `_load_snapshot_topology()`."""
    raw = json.loads(path.read_text())
    return len(raw.get("regions", [])), len(raw.get("services", []))


def validate_gcp(*, snapshot_path: Path = _GCP_SNAPSHOT_PATH) -> ValidationResult:
    topology = load_gcp_topology(snapshot_path=snapshot_path)
    problems = list(_structural_problems(topology))

    independent_regions, independent_services = _independent_gcp_recount(snapshot_path)
    if independent_regions != len(topology.regions):
        problems.append(
            f"REGION_COUNT_MISMATCH:loaded={len(topology.regions)},independent={independent_regions}"
        )
    if independent_services != len(topology.services):
        problems.append(
            f"SERVICE_COUNT_MISMATCH:loaded={len(topology.services)},independent={independent_services}"
        )

    stale, stale_reasons = _staleness(topology.fetched_at)
    return ValidationResult(
        provider="gcp",
        valid=not problems,
        problems=tuple(problems),
        stale=stale,
        stale_reasons=stale_reasons,
        independent_region_count=independent_regions,
        independent_service_count=independent_services,
        loaded_region_count=len(topology.regions),
        loaded_service_count=len(topology.services),
    )



def validate_all_topologies() -> dict[str, ValidationResult]:
    return {
        "aws": validate_aws(),
        "azure": validate_azure(),
        "gcp": validate_gcp(),
    }
