"""Real, read-only gym exposing `gymact.gyms.cloud_topology`'s
provider-published cloud data as a queryable `Environment` -- so an agent
with no prior cloud knowledge can ask "what regions/services does this
provider actually have" and get the real, published answer, not a
simulated approximation (see `cloud_topology.py`'s own module docstring for
why `multicloud.py`/`cloudsim` don't already provide this).

Every capability here is `Consequence.READ` -- this gym never actuates
anything; it only answers questions against the real, already-loaded
topology data. `requires_authority` defaults `False`: reading a cloud
provider's own public region/service catalog carries no real consequence
to gate.

GENERATED by ggen from ggen/cloud-topology-validation-pack/ontology.ttl -- do not hand-edit.
The capability catalog (iri/title/binding, in cv:capabilityOrder) is echoed from that
ontology's cv:GymCapability individuals; adding a capability means adding an individual
there (and, if it needs genuinely new actuate() logic, a new branch in this pack's
templates/cloud_topology_gym.py.tmpl), never hand-editing this file directly.
"""

from __future__ import annotations

from dataclasses import asdict
from typing import Any
from uuid import uuid4

from gymact.models import Capability, Consequence, CostDimension

from . import cloud_topology_validation
from .cloud_topology import CloudTopology, load_topology
from .cloud_topology_validation import ValidationResult

CLOUD_TOPOLOGY_CAPABILITIES: tuple[Capability, ...] = (
    Capability(
        iri="urn:gymact:cloud-topology:capability:list_regions",
        title="List every real region this provider publishes (payload: {})",
        consequence=Consequence.READ,
        binding="list_regions",
    ),
    Capability(
        iri="urn:gymact:cloud-topology:capability:list_services",
        title="List every real service/service-tag this provider publishes (payload: {})",
        consequence=Consequence.READ,
        binding="list_services",
    ),
    Capability(
        iri="urn:gymact:cloud-topology:capability:services_in_region",
        title="List real services available in a given real region (payload: {'region': str})",
        consequence=Consequence.READ,
        binding="services_in_region",
    ),
    Capability(
        iri="urn:gymact:cloud-topology:capability:validate_topology",
        title="Independently validate this provider's loaded topology via cloud_topology_validation.py (ggen-generated) -- structural invariants + a real recount via a separate code path, never just 'it loaded' (payload: {})",
        consequence=Consequence.READ,
        binding="validate_topology",
    ),
    Capability(
        iri="urn:gymact:cloud-topology:capability:estimated_managed_k8s_cost",
        title="Real published USD/hour control-plane cost of this provider's managed Kubernetes offering -- a declared estimate, not a live-billed figure (payload: {})",
        consequence=Consequence.READ,
        binding="estimated_managed_k8s_cost",
        costs=(
            CostDimension(
                unit="usd",
                quantity=0.1,
                kind="declared_estimate",
                source="managed-k8s-control-plane-hourly-fee-public-pricing",
            ),
        ),
    ),
)
_CAPABILITY_BY_BINDING = {c.binding: c for c in CLOUD_TOPOLOGY_CAPABILITIES}

#: Real, ontology-sourced managed-Kubernetes hourly control-plane cost per
#: provider -- echoed from cv:CloudProvider's cv:managedK8sHourlyCostUsd.
_MANAGED_K8S_COST_USD: dict[str, float] = {
    "aws": 0.1,
    "azure": 0.1,
    "gcp": 0.1,
}
_MANAGED_K8S_COST_SOURCE: dict[str, str] = {
    "aws": "aws-eks-cluster-hourly-fee-public-pricing",
    "azure": "azure-aks-standard-tier-hourly-fee-public-pricing",
    "gcp": "gcp-gke-cluster-management-fee-public-pricing",
}


class CloudTopologyEnvironment:
    """A materialized, real, provider-published cloud topology for one
    real provider (`"aws"`, `"azure"`, or `"gcp"`)."""

    def __init__(self, *, provider: str, requires_authority: bool = False) -> None:
        self.environment_id = f"urn:gymact:cloud-topology:environment:{uuid4().hex}"
        self.requires_authority = requires_authority
        self.provider = provider
        self._topology: CloudTopology = load_topology(provider)
        self._closed = False

    def _ensure_open(self) -> None:
        if self._closed:
            raise RuntimeError("environment is torn down")

    def capabilities(self) -> tuple[Capability, ...]:
        self._ensure_open()
        return CLOUD_TOPOLOGY_CAPABILITIES

    def _validate(self) -> ValidationResult:
        validator = getattr(cloud_topology_validation, f"validate_{self.provider}")
        return validator()

    def _state(self) -> dict[str, Any]:
        result = self._validate()
        return {
            "provider": self._topology.provider,
            "region_count": len(self._topology.regions),
            "service_count": len(self._topology.services),
            "source_url": self._topology.source_url,
            "source_version": self._topology.source_version,
            "fetched_at": self._topology.fetched_at,
            "validated": result.valid,
            "stale": result.stale,
        }

    async def observe(self) -> dict[str, Any]:
        self._ensure_open()
        return self._state()

    async def actuate(self, capability: Capability, payload: dict[str, Any]) -> dict[str, Any]:
        self._ensure_open()
        before = self._state()
        binding = capability.binding
        if binding == "list_regions":
            result: Any = list(self._topology.region_codes())
        elif binding == "list_services":
            result = list(self._topology.service_names())
        elif binding == "services_in_region":
            region = payload.get("region")
            if not isinstance(region, str) or not region:
                raise ValueError("payload.region must be a non-empty string")
            result = list(self._topology.services_in_region(region))
        elif binding == "validate_topology":
            result = asdict(self._validate())
        elif binding == "estimated_managed_k8s_cost":
            result = {
                "provider": self.provider,
                "unit": "usd",
                "quantity_per_hour": _MANAGED_K8S_COST_USD.get(self.provider),
                "source": _MANAGED_K8S_COST_SOURCE.get(self.provider),
            }
        else:
            raise ValueError(f"unsupported cloud-topology binding: {binding}")
        return {
            "before": before,
            "after": self._state(),
            "capability": capability.iri,
            "result": result,
        }

    async def verify(self, expected: dict[str, Any]) -> tuple[bool, dict[str, Any]]:
        self._ensure_open()
        observed = self._state()
        passed = all(observed.get(key) == value for key, value in expected.items())
        return passed, observed

    async def checkpoint(self) -> dict[str, Any]:
        self._ensure_open()
        # The real topology is immutable once loaded (read-only gym, no
        # actuation mutates it) -- a checkpoint has nothing real to capture
        # beyond identity.
        return {"provider": self.provider}

    async def restore(self, checkpoint: dict[str, Any]) -> None:
        self._ensure_open()
        if checkpoint.get("provider") != self.provider:
            raise ValueError("checkpoint belongs to a different provider")

    async def teardown(self) -> None:
        self._closed = True


class CloudTopologyProvider:
    """GymAct `EnvironmentProvider` materializing a real,
    provider-published `CloudTopologyEnvironment`."""

    name = "cloud-topology"
    materialization_requires_authority = False

    async def materialize(
        self, *, scenario: str | None, config: dict[str, Any]
    ) -> CloudTopologyEnvironment:
        provider = scenario or config.get("provider", "aws")
        if not isinstance(provider, str):
            raise TypeError("config.provider must be a string")
        requires_authority = config.get("requires_authority", False)
        if not isinstance(requires_authority, bool):
            raise TypeError("config.requires_authority must be a boolean")
        return CloudTopologyEnvironment(provider=provider, requires_authority=requires_authority)
