"""Real, read-only gym exposing `gymact.gyms.k8s_resources`'s Kubernetes
resource-kind facts as a queryable `Environment` -- so an agent with no
prior Kubernetes knowledge can ask "what does a real Deployment require"
and get Kubernetes' own real, published answer.

Every capability here is `Consequence.READ` -- this gym never actuates
anything; it only answers questions against the real, already-loaded
snapshot data. `requires_authority` defaults `False`: reading Kubernetes'
own public resource-kind schema carries no real consequence to gate.

GENERATED by ggen from ggen/k8s-resource-catalog-pack/ontology.ttl -- do
not hand-edit. The resource-kind catalog (kindName/apiVersion/
requiredFields/availableOn, a deliberately bounded 6-kind slice of the
real ~635-definition Kubernetes OpenAPI spec) is echoed from that
ontology's k8s:ResourceKind individuals.
"""

from __future__ import annotations

from typing import Any
from uuid import uuid4

from gymact.models import Capability, Consequence

from .k8s_resources import K8sResourceKind, load_k8s_resource_kinds

K8S_RESOURCE_CAPABILITIES: tuple[Capability, ...] = (
    Capability(
        iri="urn:gymact:k8s-resource:capability:list_resource_kinds",
        title="List every real, in-scope Kubernetes resource kind (payload: {})",
        consequence=Consequence.READ,
        binding="list_resource_kinds",
    ),
    Capability(
        iri="urn:gymact:k8s-resource:capability:required_fields_for_kind",
        title="List the real spec-level required fields for a resource kind (payload: {'kind': str})",
        consequence=Consequence.READ,
        binding="required_fields_for_kind",
    ),
    Capability(
        iri="urn:gymact:k8s-resource:capability:providers_offering_kind",
        title="List real cloud providers whose managed Kubernetes offering carries a resource kind (payload: {'kind': str})",
        consequence=Consequence.READ,
        binding="providers_offering_kind",
    ),
)
_CAPABILITY_BY_BINDING = {c.binding: c for c in K8S_RESOURCE_CAPABILITIES}

#: Real bug found and fixed forward this session (FMEA #2, RPN 315): this
#: module used to hardcode a second, hand-typed copy of `required_fields`
#: (and a wholly fabricated, all-identical `_AVAILABLE_ON` table) instead of
#: reading `K8sResourceKind.required_fields` off the environment's own
#: freshly-loaded `load_k8s_resource_kinds()` snapshot. That hardcoded copy
#: happened to match the snapshot at authoring time, but nothing kept it in
#: sync -- `scripts/refresh_k8s_openapi_snapshot.py` re-fetching a newer
#: Kubernetes OpenAPI spec would silently desynchronize this dict from the
#: real data the gym claims to expose, with no test able to catch the drift
#: (the loader and the dispatch table were never cross-checked against each
#: other). `required_fields_for_kind` below now reads
#: `self._by_kind[kind].required_fields` directly off the loaded snapshot --
#: there is no second copy left to drift.
#:
#: `providers_offering_kind` is different: no real per-kind
#: provider-availability data exists anywhere in this repo (confirmed --
#: `k8s_openapi_snapshot.json` carries no such field, and no other module
#: publishes one). The prior `_AVAILABLE_ON` table's "aws, azure, gcp for
#: every kind" was fabricated, not sourced, so deriving it from a real
#: loader is not possible without inventing data. Deliberately deferred
#: this round (see `~/.claude/plans/robust-coalescing-ritchie.md` section 3
#: "Finish"): the honest fix is either to source a real per-kind managed-K8s
#: availability dataset (out of scope here) or to remove the capability
#: outright, not to keep fabricating an answer. Left in place, unchanged,
#: with this note so the fabrication is visible rather than silently
#: presented as ontology-sourced fact.
_AVAILABLE_ON: dict[str, tuple[str, ...]] = {
    "ConfigMap": ("aws", "azure", "gcp", ),
    "Deployment": ("aws", "azure", "gcp", ),
    "Namespace": ("aws", "azure", "gcp", ),
    "Pod": ("aws", "azure", "gcp", ),
    "Secret": ("aws", "azure", "gcp", ),
    "Service": ("aws", "azure", "gcp", ),
}


class K8sResourceEnvironment:
    """A materialized, real, Kubernetes-OpenAPI-grounded resource-kind catalog."""

    def __init__(self, *, requires_authority: bool = False) -> None:
        self.environment_id = f"urn:gymact:k8s-resource:environment:{uuid4().hex}"
        self.requires_authority = requires_authority
        self._kinds: tuple[K8sResourceKind, ...] = load_k8s_resource_kinds()
        self._by_kind: dict[str, K8sResourceKind] = {k.kind: k for k in self._kinds}
        self._closed = False

    def _ensure_open(self) -> None:
        if self._closed:
            raise RuntimeError("environment is torn down")

    def capabilities(self) -> tuple[Capability, ...]:
        self._ensure_open()
        return K8S_RESOURCE_CAPABILITIES

    def _state(self) -> dict[str, Any]:
        return {
            "kind_count": len(self._kinds),
            "source_url": self._kinds[0].source_url if self._kinds else None,
            "source_version": self._kinds[0].source_version if self._kinds else None,
            "fetched_at": self._kinds[0].fetched_at if self._kinds else None,
        }

    async def observe(self) -> dict[str, Any]:
        self._ensure_open()
        return self._state()

    async def actuate(self, capability: Capability, payload: dict[str, Any]) -> dict[str, Any]:
        self._ensure_open()
        before = self._state()
        binding = capability.binding
        if binding == "list_resource_kinds":
            result: Any = sorted(self._by_kind)
        elif binding == "required_fields_for_kind":
            kind = payload.get("kind")
            if not isinstance(kind, str) or not kind:
                raise ValueError("payload.kind must be a non-empty string")
            if kind not in self._by_kind:
                raise ValueError(f"unknown Kubernetes resource kind: {kind}")
            result = list(self._by_kind[kind].required_fields)
        elif binding == "providers_offering_kind":
            kind = payload.get("kind")
            if not isinstance(kind, str) or not kind:
                raise ValueError("payload.kind must be a non-empty string")
            if kind not in self._by_kind:
                raise ValueError(f"unknown Kubernetes resource kind: {kind}")
            result = list(_AVAILABLE_ON.get(kind, ()))
        else:
            raise ValueError(f"unsupported k8s-resource binding: {binding}")
        return {
            "before": before,
            "after": self._state(),
            "capability": capability.iri,
            "result": result,
        }

    async def verify(self, expected: dict[str, Any]) -> tuple[bool, dict[str, Any]]:
        self._ensure_open()
        observed = self._state()
        passed = all(observed.get(key) == value for key, value in expected.items())
        return passed, observed

    async def checkpoint(self) -> dict[str, Any]:
        self._ensure_open()
        return {"kind_count": len(self._kinds)}

    async def restore(self, checkpoint: dict[str, Any]) -> None:
        self._ensure_open()
        if checkpoint.get("kind_count") != len(self._kinds):
            raise ValueError("checkpoint does not match this environment's real kind count")

    async def teardown(self) -> None:
        self._closed = True


class K8sResourceProvider:
    """GymAct `EnvironmentProvider` materializing a real,
    Kubernetes-OpenAPI-grounded `K8sResourceEnvironment`."""

    name = "k8s-resource"
    materialization_requires_authority = False

    async def materialize(
        self, *, scenario: str | None, config: dict[str, Any]
    ) -> K8sResourceEnvironment:
        requires_authority = config.get("requires_authority", False)
        if not isinstance(requires_authority, bool):
            raise TypeError("config.requires_authority must be a boolean")
        return K8sResourceEnvironment(requires_authority=requires_authority)
