from __future__ import annotations


class Refused(ValueError):
    """Fail-closed refusal carrying a stable machine-readable code."""

    def __init__(self, code: str, detail: str = "") -> None:
        self.code = code
        self.detail = detail
        super().__init__(f"{code}: {detail}" if detail else code)


REFUSED_INEXACT_SUBJECT = "REFUSED_INEXACT_SUBJECT"
REFUSED_INVALID_BOUND = "REFUSED_INVALID_BOUND"
REFUSED_INVALID_GAMMA = "REFUSED_INVALID_GAMMA"
REFUSED_INVALID_CASE = "REFUSED_INVALID_CASE"
REFUSED_INSUFFICIENT_SUPPORT = "REFUSED_INSUFFICIENT_SUPPORT"
REFUSED_NON_MONOTONE_ENVELOPE = "REFUSED_NON_MONOTONE_ENVELOPE"
REFUSED_UNPROVEN_INDEPENDENCE = "REFUSED_UNPROVEN_INDEPENDENCE"
REFUSED_DIVERGENT_FRONTIER = "REFUSED_DIVERGENT_FRONTIER"
REFUSED_STALE_CALIBRATION = "REFUSED_STALE_CALIBRATION"
REFUSED_UNINFORMATIVE_BOUND = "REFUSED_UNINFORMATIVE_BOUND"
REFUSED_UNRECEIPTED_ACTUATION = "REFUSED_UNRECEIPTED_ACTUATION"
