_commit: v2.5.1
_src_path: gh:kenlhlui/substrate
data_project_dirs: true
docs_with_reference: true
license: MIT
project_description: Benchmark Gym Actuation
project_name: gymact
project_type: package
project_url: https://github.com/seanchatmangpt/gymact
pydocstyle: google
python_version: '3.13'
typing: strict
version_scheme: pep440
with_conventional_commits: true
with_httpx2: true
with_pydantic: true
with_pypi_publish: true
with_typer_cli: true
