#!/usr/bin/env python3
"""A genuinely novel, freshly-invented stateful puzzle device -- the
"chronolock" -- created for a Level 4 procedure-discovery experiment. This
file and its solution have never existed before this session; nothing about
it can be present in any model's pretraining data. It is a real, executable
black-box: interact with it only via the CLI protocol below (stdin commands,
stdout observations) -- do not read this source file if you are the
discovery agent for this experiment.

Real mechanics (invented, arbitrary, not derived from any known puzzle):

Five levers: flux, torsion, cadence, umbra, verge.
Each `pull <lever>` either:
  - advances real internal progress by one step, if it is the correct next
    lever in the hidden unlock sequence, and reports "click" plus the new
    progress count, or
  - resets real progress to 0 and reports "reset", if it is the wrong lever.
A `status` command reports the real current progress count and whether the
lock is open (progress == 5, the sequence length).
The hidden correct sequence is: cadence, verge, flux, umbra, torsion --
generated by a real, fixed random permutation seeded once for this session
and never previously written down anywhere before this file.

Protocol (line-based, one command per line on stdin, one JSON observation
per line on stdout):
  probe            -> {"levers": ["flux","torsion","cadence","umbra","verge"]}
  pull <lever>     -> {"result": "click"|"reset"|"error", "progress": int, "open": bool}
  status           -> {"progress": int, "open": bool}
  quit             -> process exits
"""
from __future__ import annotations

import json
import sys

SEQUENCE = ["cadence", "verge", "flux", "umbra", "torsion"]
LEVERS = ["flux", "torsion", "cadence", "umbra", "verge"]


def main() -> None:
    progress = 0
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        parts = line.split()
        cmd = parts[0]
        if cmd == "quit":
            return
        if cmd == "probe":
            print(json.dumps({"levers": LEVERS}), flush=True)
        elif cmd == "status":
            print(json.dumps({"progress": progress, "open": progress == len(SEQUENCE)}), flush=True)
        elif cmd == "pull" and len(parts) == 2 and parts[1] in LEVERS:
            lever = parts[1]
            if progress < len(SEQUENCE) and lever == SEQUENCE[progress]:
                progress += 1
                print(json.dumps({"result": "click", "progress": progress, "open": progress == len(SEQUENCE)}), flush=True)
            else:
                progress = 0
                print(json.dumps({"result": "reset", "progress": progress, "open": False}), flush=True)
        else:
            print(json.dumps({"result": "error", "progress": progress, "open": progress == len(SEQUENCE)}), flush=True)


if __name__ == "__main__":
    main()
