"""Test-conventional import point for the fail-real/allow-degraded contract.

The contract itself lives in `gymact.standing` (production code, not test
infrastructure) so adapters can share it too -- see that module's docstring.

Allocation tracing is intentionally enabled for the current integration court:
the exact-head Python matrix treats ResourceWarning as an error and has observed
unclosed sockets/event loops/AnyIO streams whose finalizers fire during unrelated
later tests. Tracing does not suppress or reclassify those warnings; it preserves
the strict failure while binding each leaked resource to its allocation site so
the owning lifecycle can be repaired rather than guessed at.

The teardown hook below establishes the complementary deterministic collection
boundary. It runs after pytest has torn down the test's fixtures (including
pytest-asyncio's function-scoped runner/event-loop lifecycle) rather than from an
autouse fixture finalizer that can run while those resources are still lawfully
owned. Pytest's unraisable-exception wrapper still observes warnings produced by
the collection, so real leaks remain failures; only premature collection of
still-owned fixture resources is removed.
"""

from __future__ import annotations

import gc
import tracemalloc

import pytest

from gymact.standing import require_standing as require_standing

# Five frames retain the owning allocation edge without turning the full
# 953-test matrix into a tracing benchmark. This is diagnostic evidence only:
# warnings remain errors and no standing is promoted by tracing itself.
if not tracemalloc.is_tracing():
    tracemalloc.start(5)


@pytest.hookimpl(trylast=True)
def pytest_runtest_teardown(item: pytest.Item, nextitem: pytest.Item | None) -> None:
    """Collect unreachable resources only after normal fixture teardown.

    `trylast=True` places this non-wrapper hook after pytest's ordinary teardown
    implementation has released function-scoped fixtures. Pytest's own
    unraisable-exception hook wraps the teardown call and therefore still sees
    ResourceWarning/PytestUnraisableExceptionWarning generated by this explicit
    collection. No warning is filtered, caught, downgraded, or ignored.
    """
    del item, nextitem
    gc.collect()


__all__ = ["require_standing"]