# Copyright (c) AIRBUS and its affiliates.
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

"""Chicago-style tests for `gymact.gyms.k8s_resource_gym` -- real collaborators
throughout (the real bundled Kubernetes OpenAPI snapshot, a real
`K8sResourceEnvironment`/`K8sResourceProvider` lifecycle). No
`unittest.mock` / `Mock` / `MagicMock` / `patch` / `monkeypatch` anywhere
in this file.

GENERATED by ggen from ggen/k8s-resource-catalog-pack/ontology.ttl -- do
not hand-edit; the resource-kind list this file asserts over is echoed
from the same ontology the gym module itself is rendered from.
"""

from __future__ import annotations

import asyncio

import pytest

from gymact.gyms.k8s_resource_gym import (
    K8S_RESOURCE_CAPABILITIES,
    K8sResourceEnvironment,
    K8sResourceProvider,
)


def test_capability_catalog_covers_every_real_kind_operation() -> None:
    bindings = {c.binding for c in K8S_RESOURCE_CAPABILITIES}
    assert bindings == {
        "list_resource_kinds",
        "required_fields_for_kind",
        "providers_offering_kind",
    }


def test_environment_lists_the_real_bounded_kind_set() -> None:
    async def _run() -> list[str]:
        env = K8sResourceEnvironment()
        cap = next(c for c in K8S_RESOURCE_CAPABILITIES if c.binding == "list_resource_kinds")
        out = await env.actuate(cap, {})
        return out["result"]

    result = asyncio.run(_run())
    assert result == sorted(
        [
            "ConfigMap",
            "Deployment",
            "Namespace",
            "Pod",
            "Secret",
            "Service",
        ]
    )


def test_required_fields_for_configmap_is_real() -> None:
    async def _run() -> list[str]:
        env = K8sResourceEnvironment()
        cap = next(c for c in K8S_RESOURCE_CAPABILITIES if c.binding == "required_fields_for_kind")
        out = await env.actuate(cap, {"kind": "ConfigMap"})
        return out["result"]

    result = asyncio.run(_run())
    assert isinstance(result, list)


def test_providers_offering_configmap_is_real() -> None:
    async def _run() -> list[str]:
        env = K8sResourceEnvironment()
        cap = next(c for c in K8S_RESOURCE_CAPABILITIES if c.binding == "providers_offering_kind")
        out = await env.actuate(cap, {"kind": "ConfigMap"})
        return out["result"]

    result = asyncio.run(_run())
    assert set(result) <= {"aws", "azure", "gcp"}

def test_required_fields_for_deployment_is_real() -> None:
    async def _run() -> list[str]:
        env = K8sResourceEnvironment()
        cap = next(c for c in K8S_RESOURCE_CAPABILITIES if c.binding == "required_fields_for_kind")
        out = await env.actuate(cap, {"kind": "Deployment"})
        return out["result"]

    result = asyncio.run(_run())
    assert isinstance(result, list)


def test_providers_offering_deployment_is_real() -> None:
    async def _run() -> list[str]:
        env = K8sResourceEnvironment()
        cap = next(c for c in K8S_RESOURCE_CAPABILITIES if c.binding == "providers_offering_kind")
        out = await env.actuate(cap, {"kind": "Deployment"})
        return out["result"]

    result = asyncio.run(_run())
    assert set(result) <= {"aws", "azure", "gcp"}

def test_required_fields_for_namespace_is_real() -> None:
    async def _run() -> list[str]:
        env = K8sResourceEnvironment()
        cap = next(c for c in K8S_RESOURCE_CAPABILITIES if c.binding == "required_fields_for_kind")
        out = await env.actuate(cap, {"kind": "Namespace"})
        return out["result"]

    result = asyncio.run(_run())
    assert isinstance(result, list)


def test_providers_offering_namespace_is_real() -> None:
    async def _run() -> list[str]:
        env = K8sResourceEnvironment()
        cap = next(c for c in K8S_RESOURCE_CAPABILITIES if c.binding == "providers_offering_kind")
        out = await env.actuate(cap, {"kind": "Namespace"})
        return out["result"]

    result = asyncio.run(_run())
    assert set(result) <= {"aws", "azure", "gcp"}

def test_required_fields_for_pod_is_real() -> None:
    async def _run() -> list[str]:
        env = K8sResourceEnvironment()
        cap = next(c for c in K8S_RESOURCE_CAPABILITIES if c.binding == "required_fields_for_kind")
        out = await env.actuate(cap, {"kind": "Pod"})
        return out["result"]

    result = asyncio.run(_run())
    assert isinstance(result, list)


def test_providers_offering_pod_is_real() -> None:
    async def _run() -> list[str]:
        env = K8sResourceEnvironment()
        cap = next(c for c in K8S_RESOURCE_CAPABILITIES if c.binding == "providers_offering_kind")
        out = await env.actuate(cap, {"kind": "Pod"})
        return out["result"]

    result = asyncio.run(_run())
    assert set(result) <= {"aws", "azure", "gcp"}

def test_required_fields_for_secret_is_real() -> None:
    async def _run() -> list[str]:
        env = K8sResourceEnvironment()
        cap = next(c for c in K8S_RESOURCE_CAPABILITIES if c.binding == "required_fields_for_kind")
        out = await env.actuate(cap, {"kind": "Secret"})
        return out["result"]

    result = asyncio.run(_run())
    assert isinstance(result, list)


def test_providers_offering_secret_is_real() -> None:
    async def _run() -> list[str]:
        env = K8sResourceEnvironment()
        cap = next(c for c in K8S_RESOURCE_CAPABILITIES if c.binding == "providers_offering_kind")
        out = await env.actuate(cap, {"kind": "Secret"})
        return out["result"]

    result = asyncio.run(_run())
    assert set(result) <= {"aws", "azure", "gcp"}

def test_required_fields_for_service_is_real() -> None:
    async def _run() -> list[str]:
        env = K8sResourceEnvironment()
        cap = next(c for c in K8S_RESOURCE_CAPABILITIES if c.binding == "required_fields_for_kind")
        out = await env.actuate(cap, {"kind": "Service"})
        return out["result"]

    result = asyncio.run(_run())
    assert isinstance(result, list)


def test_providers_offering_service_is_real() -> None:
    async def _run() -> list[str]:
        env = K8sResourceEnvironment()
        cap = next(c for c in K8S_RESOURCE_CAPABILITIES if c.binding == "providers_offering_kind")
        out = await env.actuate(cap, {"kind": "Service"})
        return out["result"]

    result = asyncio.run(_run())
    assert set(result) <= {"aws", "azure", "gcp"}


def test_unknown_kind_raises_real_value_error() -> None:
    async def _run() -> None:
        env = K8sResourceEnvironment()
        cap = next(c for c in K8S_RESOURCE_CAPABILITIES if c.binding == "required_fields_for_kind")
        await env.actuate(cap, {"kind": "NotARealKind"})

    with pytest.raises(ValueError):
        asyncio.run(_run())


def test_full_provider_lifecycle_is_real() -> None:
    async def _run() -> None:
        provider = K8sResourceProvider()
        env = await provider.materialize(scenario=None, config={})
        observed = await env.observe()
        assert observed["kind_count"] == 6
        checkpoint = await env.checkpoint()
        await env.restore(checkpoint)
        await env.teardown()

    asyncio.run(_run())
