# Copyright (c) AIRBUS and its affiliates.
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

"""Chicago-style tests for `gymact.gyms.cloud_topology_validation` -- real collaborators
throughout (real `botocore` data, real bundled snapshot files, real hand-constructed
`CloudTopology` objects for the negative structural tests). No `unittest.mock` / `Mock` /
`MagicMock` / `patch` / `monkeypatch` anywhere in this file.

GENERATED by ggen from ggen/cloud-topology-validation-pack/ontology.ttl -- do not hand-edit;
the provider list this file asserts over is echoed from the same ontology the validator
module itself is rendered from, so the two can never silently drift apart.
"""

from __future__ import annotations

from gymact.gyms.cloud_topology import CloudRegion, CloudService, CloudTopology
from gymact.gyms.cloud_topology_validation import (
    ValidationResult,
    _structural_problems,
    validate_all_topologies,
    validate_aws,
    validate_azure,
    validate_gcp,
)


def test_validate_all_topologies_covers_every_real_provider() -> None:
    results = validate_all_topologies()
    assert set(results.keys()) == {
        "aws",
        "azure",
        "gcp",
    }
    for provider, result in results.items():
        assert isinstance(result, ValidationResult)
        assert result.provider == provider


def test_validate_aws_real_run_is_structurally_valid() -> None:
    """A real run against the currently-loaded aws data must be free of
    structural problems -- this is the real regression guard: if `cloud_topology.py`'s loader
    ever reintroduces a dangling reference or a count mismatch, this test fails for real,
    not synthetically."""
    result = validate_aws()
    assert result.problems == (), f"real aws validation problems: {result.problems}"
    assert result.valid is True
    assert result.independent_region_count == result.loaded_region_count
    assert result.independent_service_count == result.loaded_service_count

def test_validate_azure_real_run_is_structurally_valid() -> None:
    """A real run against the currently-loaded azure data must be free of
    structural problems -- this is the real regression guard: if `cloud_topology.py`'s loader
    ever reintroduces a dangling reference or a count mismatch, this test fails for real,
    not synthetically."""
    result = validate_azure()
    assert result.problems == (), f"real azure validation problems: {result.problems}"
    assert result.valid is True
    assert result.independent_region_count == result.loaded_region_count
    assert result.independent_service_count == result.loaded_service_count

def test_validate_gcp_real_run_is_structurally_valid() -> None:
    """A real run against the currently-loaded gcp data must be free of
    structural problems -- this is the real regression guard: if `cloud_topology.py`'s loader
    ever reintroduces a dangling reference or a count mismatch, this test fails for real,
    not synthetically."""
    result = validate_gcp()
    assert result.problems == (), f"real gcp validation problems: {result.problems}"
    assert result.valid is True
    assert result.independent_region_count == result.loaded_region_count
    assert result.independent_service_count == result.loaded_service_count



def test_structural_problems_catches_a_real_dangling_region_reference() -> None:
    """Real, hand-constructed negative case: a service claims availability in a region code
    that does not exist anywhere in `topology.regions` -- the exact real defect class the AWS
    loader shipped this session (229 pseudo-region endpoint-alias keys). Must be caught."""
    broken = CloudTopology(
        provider="aws",
        regions=(CloudRegion(provider="aws", code="us-east-1"),),
        services=(CloudService(provider="aws", name="s3"),),
        service_region_availability={"s3": ("us-east-1", "not-a-real-region")},
        source_url="test-fixture",
    )
    problems = _structural_problems(broken)
    assert "DANGLING_REGION_REFERENCE:s3->not-a-real-region" in problems


def test_structural_problems_catches_duplicate_region_code() -> None:
    broken = CloudTopology(
        provider="aws",
        regions=(
            CloudRegion(provider="aws", code="us-east-1"),
            CloudRegion(provider="aws", code="us-east-1"),
        ),
        services=(),
        service_region_availability={},
        source_url="test-fixture",
    )
    assert "DUPLICATE_REGION_CODE" in _structural_problems(broken)


def test_structural_problems_catches_cross_provider_region() -> None:
    broken = CloudTopology(
        provider="aws",
        regions=(CloudRegion(provider="azure", code="eastus"),),
        services=(),
        service_region_availability={},
        source_url="test-fixture",
    )
    assert "CROSS_PROVIDER_REGION:eastus" in _structural_problems(broken)


def test_structural_problems_zero_services_exempts_degenerate_providers() -> None:
    """Real, ontology-sourced exception: providers with cv:hasDegenerateServices=true must
    not raise ZERO_SERVICES for an empty services tuple."""
    degenerate = CloudTopology(
        provider="gcp",
        regions=(CloudRegion(provider="gcp", code="r1"),),
        services=(),
        service_region_availability={},
        source_url="test-fixture",
    )
    assert "ZERO_SERVICES" not in _structural_problems(degenerate)


def test_structural_problems_zero_services_flags_non_degenerate_providers() -> None:
    non_degenerate = CloudTopology(
        provider="aws",
        regions=(CloudRegion(provider="aws", code="r1"),),
        services=(),
        service_region_availability={},
        source_url="test-fixture",
    )
    assert "ZERO_SERVICES" in _structural_problems(non_degenerate)
    non_degenerate = CloudTopology(
        provider="azure",
        regions=(CloudRegion(provider="azure", code="r1"),),
        services=(),
        service_region_availability={},
        source_url="test-fixture",
    )
    assert "ZERO_SERVICES" in _structural_problems(non_degenerate)

