"""GENERATED by ggen from public-ontology-admission-pack/ontology.ttl -- do not hand-edit.

Chicago-style: real `is_admitted`/`classify` calls against the real generated registry, no
mocks. Proves both directions of the PUBLIC-ONLY ADMISSION policy: every ontology-admitted
class IRI is recognized, and an invented private class IRI is refused.
"""

from __future__ import annotations

from gymact.semantics.admission import SourceKind, classify, is_admitted

ONTOLOGY_ADMITTED_CLASS_IRIS = [
"http://www.w3.org/2004/02/skos/core#Collection",
"http://www.w3.org/2004/02/skos/core#Concept",
"http://www.w3.org/2004/02/skos/core#ConceptScheme",
"http://www.w3.org/2004/02/skos/core#OrderedCollection",
"http://www.w3.org/ns/dcat#Catalog",
"http://www.w3.org/ns/dcat#CatalogRecord",
"http://www.w3.org/ns/dcat#DataService",
"http://www.w3.org/ns/dcat#Dataset",
"http://www.w3.org/ns/dcat#DatasetSeries",
"http://www.w3.org/ns/dcat#Distribution",
"http://www.w3.org/ns/dcat#Relationship",
"http://www.w3.org/ns/dcat#Resource",
"http://www.w3.org/ns/dcat#Role",
"http://www.w3.org/ns/dqv#Category",
"http://www.w3.org/ns/dqv#Dimension",
"http://www.w3.org/ns/dqv#Metric",
"http://www.w3.org/ns/dqv#QualityAnnotation",
"http://www.w3.org/ns/dqv#QualityCertificate",
"http://www.w3.org/ns/dqv#QualityMeasurement",
"http://www.w3.org/ns/dqv#QualityMeasurementDataset",
"http://www.w3.org/ns/dqv#QualityMetadata",
"http://www.w3.org/ns/dqv#QualityPolicy",
"http://www.w3.org/ns/dqv#UserQualityFeedback",
"http://www.w3.org/ns/org#ChangeEvent",
"http://www.w3.org/ns/org#FormalOrganization",
"http://www.w3.org/ns/org#Membership",
"http://www.w3.org/ns/org#Organization",
"http://www.w3.org/ns/org#OrganizationalCollaboration",
"http://www.w3.org/ns/org#OrganizationalUnit",
"http://www.w3.org/ns/org#Post",
"http://www.w3.org/ns/org#Role",
"http://www.w3.org/ns/org#Site",
"http://www.w3.org/ns/prov#Activity",
"http://www.w3.org/ns/prov#ActivityInfluence",
"http://www.w3.org/ns/prov#Agent",
"http://www.w3.org/ns/prov#AgentInfluence",
"http://www.w3.org/ns/prov#Association",
"http://www.w3.org/ns/prov#Attribution",
"http://www.w3.org/ns/prov#Bundle",
"http://www.w3.org/ns/prov#Collection",
"http://www.w3.org/ns/prov#Communication",
"http://www.w3.org/ns/prov#Delegation",
"http://www.w3.org/ns/prov#Derivation",
"http://www.w3.org/ns/prov#EmptyCollection",
"http://www.w3.org/ns/prov#End",
"http://www.w3.org/ns/prov#Entity",
"http://www.w3.org/ns/prov#EntityInfluence",
"http://www.w3.org/ns/prov#Generation",
"http://www.w3.org/ns/prov#Influence",
"http://www.w3.org/ns/prov#InstantaneousEvent",
"http://www.w3.org/ns/prov#Invalidation",
"http://www.w3.org/ns/prov#Location",
"http://www.w3.org/ns/prov#Organization",
"http://www.w3.org/ns/prov#Person",
"http://www.w3.org/ns/prov#Plan",
"http://www.w3.org/ns/prov#PrimarySource",
"http://www.w3.org/ns/prov#Quotation",
"http://www.w3.org/ns/prov#Revision",
"http://www.w3.org/ns/prov#Role",
"http://www.w3.org/ns/prov#SoftwareAgent",
"http://www.w3.org/ns/prov#Start",
"http://www.w3.org/ns/prov#Usage",
"http://www.w3.org/ns/shacl#AbstractResult",
"http://www.w3.org/ns/shacl#ConstraintComponent",
"http://www.w3.org/ns/shacl#Function",
"http://www.w3.org/ns/shacl#JSConstraint",
"http://www.w3.org/ns/shacl#JSExecutable",
"http://www.w3.org/ns/shacl#JSFunction",
"http://www.w3.org/ns/shacl#JSLibrary",
"http://www.w3.org/ns/shacl#JSRule",
"http://www.w3.org/ns/shacl#JSTarget",
"http://www.w3.org/ns/shacl#JSTargetType",
"http://www.w3.org/ns/shacl#JSValidator",
"http://www.w3.org/ns/shacl#NodeKind",
"http://www.w3.org/ns/shacl#NodeShape",
"http://www.w3.org/ns/shacl#Parameter",
"http://www.w3.org/ns/shacl#Parameterizable",
"http://www.w3.org/ns/shacl#PrefixDeclaration",
"http://www.w3.org/ns/shacl#PropertyGroup",
"http://www.w3.org/ns/shacl#PropertyShape",
"http://www.w3.org/ns/shacl#ResultAnnotation",
"http://www.w3.org/ns/shacl#Rule",
"http://www.w3.org/ns/shacl#SPARQLAskExecutable",
"http://www.w3.org/ns/shacl#SPARQLAskValidator",
"http://www.w3.org/ns/shacl#SPARQLConstraint",
"http://www.w3.org/ns/shacl#SPARQLConstructExecutable",
"http://www.w3.org/ns/shacl#SPARQLExecutable",
"http://www.w3.org/ns/shacl#SPARQLFunction",
"http://www.w3.org/ns/shacl#SPARQLRule",
"http://www.w3.org/ns/shacl#SPARQLSelectExecutable",
"http://www.w3.org/ns/shacl#SPARQLSelectValidator",
"http://www.w3.org/ns/shacl#SPARQLTarget",
"http://www.w3.org/ns/shacl#SPARQLTargetType",
"http://www.w3.org/ns/shacl#SPARQLUpdateExecutable",
"http://www.w3.org/ns/shacl#Severity",
"http://www.w3.org/ns/shacl#Shape",
"http://www.w3.org/ns/shacl#Target",
"http://www.w3.org/ns/shacl#TargetType",
"http://www.w3.org/ns/shacl#TripleRule",
"http://www.w3.org/ns/shacl#ValidationReport",
"http://www.w3.org/ns/shacl#ValidationResult",
"http://www.w3.org/ns/shacl#Validator",
]

EXPECTED_AUTHORITY_COUNT = 6


def test_every_ontology_admitted_class_is_recognized():
    for class_iri in ONTOLOGY_ADMITTED_CLASS_IRIS:
        assert is_admitted(class_iri) is True, class_iri


def test_a_real_prov_o_class_is_admitted_as_native_ontology():
    assert is_admitted("http://www.w3.org/ns/prov#Entity") is True
    assert classify("http://www.w3.org/ns/prov#Entity") == SourceKind.NATIVE_ONTOLOGY


def test_a_real_org_class_is_admitted_as_native_ontology():
    assert is_admitted("http://www.w3.org/ns/org#Organization") is True
    assert classify("http://www.w3.org/ns/org#Organization") == SourceKind.NATIVE_ONTOLOGY


def test_an_invented_private_class_is_refused():
    """The exact failure mode the admission law exists to prevent: a made-up class like
    `SonyApplication` must never be silently treated as admitted."""
    assert is_admitted("http://sony.example/SonyApplication") is False
    assert classify("http://sony.example/SonyApplication") is None


def test_registry_has_exactly_the_real_admitted_authority_count():
    from gymact.semantics.admission import PUBLIC_AUTHORITIES

    assert len(PUBLIC_AUTHORITIES) == EXPECTED_AUTHORITY_COUNT
