"""GENERATED by ggen from public-ontology-admission-pack/ontology.ttl -- do not hand-edit.

The PUBLIC-ONLY ADMISSION policy: a class IRI is admitted only if it belongs to a real,
verified public semantic authority (a resolvable W3C/OMG/OASIS/etc namespace), never a
locally-invented private class. Every authority and class below was verified live (WebFetch
against the real specification document) before being transcribed into
public-ontology-admission-pack/ontology.ttl -- see that file's own grounding note.

Consumed identically by gymact and autofde-lab (both generated from this one pack, not
hand-duplicated).
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


class SourceKind(str, Enum):
    """Where an admitted class's semantics actually come from -- never silently relabeled."""

    NATIVE_ONTOLOGY = "NATIVE_ONTOLOGY"
    RDF_VOCABULARY = "RDF_VOCABULARY"
    NORMATIVE_METAMODEL = "NORMATIVE_METAMODEL"
    NORMATIVE_SCHEMA = "NORMATIVE_SCHEMA"
    PROTOCOL_SPECIFICATION = "PROTOCOL_SPECIFICATION"
    CONTROL_MODEL = "CONTROL_MODEL"
    PUBLIC_TAXONOMY = "PUBLIC_TAXONOMY"
    VENDOR_RESOURCE_SCHEMA = "VENDOR_RESOURCE_SCHEMA"
    DERIVED_PROJECTION = "DERIVED_PROJECTION"
    LOCAL_INSTANCE = "LOCAL_INSTANCE"


@dataclass(frozen=True)
class PublicAuthority:
    authority_id: str
    namespace_uri: str
    spec_uri: str
    publication_status: str
    source_kind: SourceKind


@dataclass(frozen=True)
class AdmittedClass:
    authority_id: str
    class_name: str
    class_iri: str
    comment: str


PUBLIC_AUTHORITIES: dict[str, PublicAuthority] = {
"dcat-3": PublicAuthority(
        authority_id="dcat-3",
        namespace_uri="http://www.w3.org/ns/dcat#",
        spec_uri="https://www.w3.org/TR/vocab-dcat-3/",
        publication_status="W3C Recommendation 2024-08-22",
        source_kind=SourceKind.NATIVE_ONTOLOGY,
    ),
"dqv": PublicAuthority(
        authority_id="dqv",
        namespace_uri="http://www.w3.org/ns/dqv#",
        spec_uri="https://www.w3.org/TR/vocab-dqv/",
        publication_status="W3C Working Group Note 2016-12-15",
        source_kind=SourceKind.NATIVE_ONTOLOGY,
    ),
"org": PublicAuthority(
        authority_id="org",
        namespace_uri="http://www.w3.org/ns/org#",
        spec_uri="https://www.w3.org/TR/vocab-org/",
        publication_status="W3C Recommendation 2014-01-16",
        source_kind=SourceKind.NATIVE_ONTOLOGY,
    ),
"prov-o": PublicAuthority(
        authority_id="prov-o",
        namespace_uri="http://www.w3.org/ns/prov#",
        spec_uri="https://www.w3.org/ns/prov-o",
        publication_status="W3C Recommendation 2013-04-30",
        source_kind=SourceKind.NATIVE_ONTOLOGY,
    ),
"shacl": PublicAuthority(
        authority_id="shacl",
        namespace_uri="http://www.w3.org/ns/shacl#",
        spec_uri="https://www.w3.org/TR/shacl/",
        publication_status="W3C Recommendation 2017-07-20",
        source_kind=SourceKind.NATIVE_ONTOLOGY,
    ),
"skos": PublicAuthority(
        authority_id="skos",
        namespace_uri="http://www.w3.org/2004/02/skos/core#",
        spec_uri="https://www.w3.org/TR/skos-reference/",
        publication_status="W3C Recommendation 2009-08-18",
        source_kind=SourceKind.NATIVE_ONTOLOGY,
    ),
}

ADMITTED_CLASSES: dict[str, AdmittedClass] = {
"http://www.w3.org/2004/02/skos/core#Collection": AdmittedClass(
        authority_id="skos",
        class_name="Collection",
        class_iri="http://www.w3.org/2004/02/skos/core#Collection",
        comment="a labeled and/or ordered group of concepts or nested collections",
    ),
"http://www.w3.org/2004/02/skos/core#Concept": AdmittedClass(
        authority_id="skos",
        class_name="Concept",
        class_iri="http://www.w3.org/2004/02/skos/core#Concept",
        comment="an idea or notion; a unit of thought within a knowledge organization system",
    ),
"http://www.w3.org/2004/02/skos/core#ConceptScheme": AdmittedClass(
        authority_id="skos",
        class_name="ConceptScheme",
        class_iri="http://www.w3.org/2004/02/skos/core#ConceptScheme",
        comment="an aggregation of one or more SKOS concepts and their semantic relationships",
    ),
"http://www.w3.org/2004/02/skos/core#OrderedCollection": AdmittedClass(
        authority_id="skos",
        class_name="OrderedCollection",
        class_iri="http://www.w3.org/2004/02/skos/core#OrderedCollection",
        comment="a specialized collection that maintains member ordering",
    ),
"http://www.w3.org/ns/dcat#Catalog": AdmittedClass(
        authority_id="dcat-3",
        class_name="Catalog",
        class_iri="http://www.w3.org/ns/dcat#Catalog",
        comment="A curated collection of metadata about resources (e.g., datasets and data services in the context of a data catalog).",
    ),
"http://www.w3.org/ns/dcat#CatalogRecord": AdmittedClass(
        authority_id="dcat-3",
        class_name="CatalogRecord",
        class_iri="http://www.w3.org/ns/dcat#CatalogRecord",
        comment="A record in a data catalog, describing the registration of a single dataset or data service.",
    ),
"http://www.w3.org/ns/dcat#DataService": AdmittedClass(
        authority_id="dcat-3",
        class_name="DataService",
        class_iri="http://www.w3.org/ns/dcat#DataService",
        comment="A site or end-point providing operations related to the discovery of, access to, or processing functions on, data or related resources.",
    ),
"http://www.w3.org/ns/dcat#Dataset": AdmittedClass(
        authority_id="dcat-3",
        class_name="Dataset",
        class_iri="http://www.w3.org/ns/dcat#Dataset",
        comment="A collection of data, published or curated by a single source, and available for access or download in one or more representations.",
    ),
"http://www.w3.org/ns/dcat#DatasetSeries": AdmittedClass(
        authority_id="dcat-3",
        class_name="DatasetSeries",
        class_iri="http://www.w3.org/ns/dcat#DatasetSeries",
        comment="A collection of datasets that are published separately, but share some characteristics that group them.",
    ),
"http://www.w3.org/ns/dcat#Distribution": AdmittedClass(
        authority_id="dcat-3",
        class_name="Distribution",
        class_iri="http://www.w3.org/ns/dcat#Distribution",
        comment="A specific representation of a dataset. A dataset might be available in multiple serializations that may differ in various ways, including natural language, media-type or format, schematic organization, temporal and spatial resolution, level of detail or profiles (which might specify any or all of the above).",
    ),
"http://www.w3.org/ns/dcat#Relationship": AdmittedClass(
        authority_id="dcat-3",
        class_name="Relationship",
        class_iri="http://www.w3.org/ns/dcat#Relationship",
        comment="An association class for attaching additional information to a relationship between DCAT Resources.",
    ),
"http://www.w3.org/ns/dcat#Resource": AdmittedClass(
        authority_id="dcat-3",
        class_name="Resource",
        class_iri="http://www.w3.org/ns/dcat#Resource",
        comment="Resource published or curated by a single agent.",
    ),
"http://www.w3.org/ns/dcat#Role": AdmittedClass(
        authority_id="dcat-3",
        class_name="Role",
        class_iri="http://www.w3.org/ns/dcat#Role",
        comment="A role is the function of a resource or agent with respect to another resource, in the context of resource attribution or resource relationships.",
    ),
"http://www.w3.org/ns/dqv#Category": AdmittedClass(
        authority_id="dqv",
        class_name="Category",
        class_iri="http://www.w3.org/ns/dqv#Category",
        comment="Represents a group of quality dimensions in which a common type of information is used as quality indicator.",
    ),
"http://www.w3.org/ns/dqv#Dimension": AdmittedClass(
        authority_id="dqv",
        class_name="Dimension",
        class_iri="http://www.w3.org/ns/dqv#Dimension",
        comment="Represents criteria relevant for assessing quality. Each quality dimension must have one or more metric to measure it. A dimension is linked with a category using the dqv:inCategory property.",
    ),
"http://www.w3.org/ns/dqv#Metric": AdmittedClass(
        authority_id="dqv",
        class_name="Metric",
        class_iri="http://www.w3.org/ns/dqv#Metric",
        comment="Represents a standard to measure a quality dimension. An observation (instance of dqv:QualityMeasurement) assigns a value in a given unit to a Metric.",
    ),
"http://www.w3.org/ns/dqv#QualityAnnotation": AdmittedClass(
        authority_id="dqv",
        class_name="QualityAnnotation",
        class_iri="http://www.w3.org/ns/dqv#QualityAnnotation",
        comment="Represents quality annotations, including ratings, quality certificates or feedback that can be associated to datasets or distributions. Quality annotations must have one oa:motivatedBy statement with an instance of oa:Motivation (and skos:Concept) that reflects a quality assessment purpose. We define this instance as dqv:qualityAssessment.",
    ),
"http://www.w3.org/ns/dqv#QualityCertificate": AdmittedClass(
        authority_id="dqv",
        class_name="QualityCertificate",
        class_iri="http://www.w3.org/ns/dqv#QualityCertificate",
        comment="An annotation that associates a resource (especially, a dataset or a distribution) to another resource (for example, a document) that certifies the resource's quality according to a set of quality assessment rules.",
    ),
"http://www.w3.org/ns/dqv#QualityMeasurement": AdmittedClass(
        authority_id="dqv",
        class_name="QualityMeasurement",
        class_iri="http://www.w3.org/ns/dqv#QualityMeasurement",
        comment="Represents the evaluation of a given dataset (or dataset distribution) against a specific quality metric.",
    ),
"http://www.w3.org/ns/dqv#QualityMeasurementDataset": AdmittedClass(
        authority_id="dqv",
        class_name="QualityMeasurementDataset",
        class_iri="http://www.w3.org/ns/dqv#QualityMeasurementDataset",
        comment="Represents a dataset of quality measurements, evaluations of one or more datasets (or dataset distributions) against specific quality metrics.",
    ),
"http://www.w3.org/ns/dqv#QualityMetadata": AdmittedClass(
        authority_id="dqv",
        class_name="QualityMetadata",
        class_iri="http://www.w3.org/ns/dqv#QualityMetadata",
        comment="Represents quality metadata, it is defined to group quality certificates, policies, measurements and annotations under a named graph.",
    ),
"http://www.w3.org/ns/dqv#QualityPolicy": AdmittedClass(
        authority_id="dqv",
        class_name="QualityPolicy",
        class_iri="http://www.w3.org/ns/dqv#QualityPolicy",
        comment="Represents a policy or agreement that is chiefly governed by data quality concerns.",
    ),
"http://www.w3.org/ns/dqv#UserQualityFeedback": AdmittedClass(
        authority_id="dqv",
        class_name="UserQualityFeedback",
        class_iri="http://www.w3.org/ns/dqv#UserQualityFeedback",
        comment="Represents feedback that users have on the quality of datasets or distributions. Besides dqv:qualityAssessment, which is the motivation required by all quality annotations, one of the predefined instances of oa:Motivation should be indicated as motivation to distinguish among the different kinds of feedback, e.g., classifications, questions.",
    ),
"http://www.w3.org/ns/org#ChangeEvent": AdmittedClass(
        authority_id="org",
        class_name="ChangeEvent",
        class_iri="http://www.w3.org/ns/org#ChangeEvent",
        comment="Represents an event which resulted in a major change to an organization such as a merger or complete restructuring. It is intended for situations where the resulting organization is sufficient distinct from the original organizations that it has a distinct identity and distinct URI. Extension vocabularies should define sub-classes of this to denote particular categories of event. The instant or interval at which the event occurred should be given by `prov:startAtTime` and `prov:endedAtTime`, a description should be given by `dct:description`. ",
    ),
"http://www.w3.org/ns/org#FormalOrganization": AdmittedClass(
        authority_id="org",
        class_name="FormalOrganization",
        class_iri="http://www.w3.org/ns/org#FormalOrganization",
        comment="An Organization which is recognized in the world at large, in particular in legal jurisdictions, with associated rights and responsibilities. Examples include a Corporation, Charity, Government or Church. Note that this is a super class of `gr:BusinessEntity` and it is recommended to use the GoodRelations vocabulary to denote Business classifications such as DUNS or NAICS.",
    ),
"http://www.w3.org/ns/org#Membership": AdmittedClass(
        authority_id="org",
        class_name="Membership",
        class_iri="http://www.w3.org/ns/org#Membership",
        comment="Indicates the nature of an Agent's membership of an organization. Represents an n-ary relation between an Agent, an Organization and a Role. It is possible to directly indicate membership, independent of the specific Role, through use of the `org:memberOf` property.",
    ),
"http://www.w3.org/ns/org#Organization": AdmittedClass(
        authority_id="org",
        class_name="Organization",
        class_iri="http://www.w3.org/ns/org#Organization",
        comment="Represents a collection of people organized together into a community or other social, commercial or political structure. The group has some common purpose or reason for existence which goes beyond the set of people belonging to it and can act as an Agent. Organizations are often decomposable into hierarchical structures.  It is recommended that SKOS lexical labels should be used to label the Organization. In particular `skos:prefLabel` for the primary (possibly legally recognized name), `skos:altLabel` for alternative names (trading names, colloquial names) and `skos:notation` to denote a code from a code list. Alternative names: _Collective_ _Body_ _Org_ _Group_",
    ),
"http://www.w3.org/ns/org#OrganizationalCollaboration": AdmittedClass(
        authority_id="org",
        class_name="OrganizationalCollaboration",
        class_iri="http://www.w3.org/ns/org#OrganizationalCollaboration",
        comment="A collaboration between two or more Organizations such as a project. It meets the criteria for being an Organization in that it has an identity and defining purpose independent of its particular members but is neither a formally recognized legal entity nor a sub-unit within some larger organization. Might typically have a shorter lifetime than the Organizations within it, but not necessarily. All members are `org:Organization`s rather than individuals and those Organizations can play particular roles within the venture. Alternative names: _Project_ _Venture_  _Endeavour_ _Consortium_ _Endeavour_",
    ),
"http://www.w3.org/ns/org#OrganizationalUnit": AdmittedClass(
        authority_id="org",
        class_name="OrganizationalUnit",
        class_iri="http://www.w3.org/ns/org#OrganizationalUnit",
        comment="An Organization such as a University Support Unit which is part of some larger FormalOrganization and only has full recognition within the context of that FormalOrganization, it is not a Legal Entity in its own right. Units can be large and complex containing other Units and even FormalOrganizations. Alternative names: _OU_ _Unit_ _Department_",
    ),
"http://www.w3.org/ns/org#Post": AdmittedClass(
        authority_id="org",
        class_name="Post",
        class_iri="http://www.w3.org/ns/org#Post",
        comment="A Post represents some position within an organization that exists independently of the person or persons filling it. Posts may be used to represent situations where a person is a member of an organization ex officio (for example the Secretary of State for Scotland is part of UK Cabinet by virtue of being Secretary of State for Scotland, not as an individual person). A post can be held by multiple people and hence can be treated as a organization in its own right.",
    ),
"http://www.w3.org/ns/org#Role": AdmittedClass(
        authority_id="org",
        class_name="Role",
        class_iri="http://www.w3.org/ns/org#Role",
        comment="Denotes a role that a Person or other Agent can take in an organization. Instances of this class describe the abstract role; to denote a specific instance of a person playing that role in a specific organization use an instance of `org:Membership`. It is common for roles to be arranged in some taxonomic structure and we use SKOS to represent that. The normal SKOS lexical properties should be used when labelling the Role. Additional descriptive properties for the Role, such as a Salary band, may be added by extension vocabularies.",
    ),
"http://www.w3.org/ns/org#Site": AdmittedClass(
        authority_id="org",
        class_name="Site",
        class_iri="http://www.w3.org/ns/org#Site",
        comment="An office or other premise at which the organization is located. Many organizations are spread across multiple sites and many sites will host multiple locations. In most cases a Site will be a physical location. However, we don't exclude the possibility of non-physical sites such as a virtual office with an associated post box and phone reception service. Extensions may provide subclasses to denote particular types of site.",
    ),
"http://www.w3.org/ns/prov#Activity": AdmittedClass(
        authority_id="prov-o",
        class_name="Activity",
        class_iri="http://www.w3.org/ns/prov#Activity",
        comment="",
    ),
"http://www.w3.org/ns/prov#ActivityInfluence": AdmittedClass(
        authority_id="prov-o",
        class_name="ActivityInfluence",
        class_iri="http://www.w3.org/ns/prov#ActivityInfluence",
        comment="It is not recommended that the type ActivityInfluence be asserted without also asserting one of its more specific subclasses.",
    ),
"http://www.w3.org/ns/prov#ActivityInfluence": AdmittedClass(
        authority_id="prov-o",
        class_name="ActivityInfluence",
        class_iri="http://www.w3.org/ns/prov#ActivityInfluence",
        comment="ActivityInfluence provides additional descriptions of an Activity's binary influence upon any other kind of resource. Instances of ActivityInfluence use the prov:activity property to cite the influencing Activity.",
    ),
"http://www.w3.org/ns/prov#Agent": AdmittedClass(
        authority_id="prov-o",
        class_name="Agent",
        class_iri="http://www.w3.org/ns/prov#Agent",
        comment="",
    ),
"http://www.w3.org/ns/prov#AgentInfluence": AdmittedClass(
        authority_id="prov-o",
        class_name="AgentInfluence",
        class_iri="http://www.w3.org/ns/prov#AgentInfluence",
        comment="It is not recommended that the type AgentInfluence be asserted without also asserting one of its more specific subclasses.",
    ),
"http://www.w3.org/ns/prov#AgentInfluence": AdmittedClass(
        authority_id="prov-o",
        class_name="AgentInfluence",
        class_iri="http://www.w3.org/ns/prov#AgentInfluence",
        comment="AgentInfluence provides additional descriptions of an Agent's binary influence upon any other kind of resource. Instances of AgentInfluence use the prov:agent property to cite the influencing Agent.",
    ),
"http://www.w3.org/ns/prov#Association": AdmittedClass(
        authority_id="prov-o",
        class_name="Association",
        class_iri="http://www.w3.org/ns/prov#Association",
        comment="An instance of prov:Association provides additional descriptions about the binary prov:wasAssociatedWith relation from an prov:Activity to some prov:Agent that had some responsiblity for it. For example, :baking prov:wasAssociatedWith :baker; prov:qualifiedAssociation [ a prov:Association; prov:agent :baker; :foo :bar ].",
    ),
"http://www.w3.org/ns/prov#Attribution": AdmittedClass(
        authority_id="prov-o",
        class_name="Attribution",
        class_iri="http://www.w3.org/ns/prov#Attribution",
        comment="An instance of prov:Attribution provides additional descriptions about the binary prov:wasAttributedTo relation from an prov:Entity to some prov:Agent that had some responsible for it. For example, :cake prov:wasAttributedTo :baker; prov:qualifiedAttribution [ a prov:Attribution; prov:entity :baker; :foo :bar ].",
    ),
"http://www.w3.org/ns/prov#Bundle": AdmittedClass(
        authority_id="prov-o",
        class_name="Bundle",
        class_iri="http://www.w3.org/ns/prov#Bundle",
        comment="Note that there are kinds of bundles (e.g. handwritten letters, audio recordings, etc.) that are not expressed in PROV-O, but can be still be described by PROV-O.",
    ),
"http://www.w3.org/ns/prov#Collection": AdmittedClass(
        authority_id="prov-o",
        class_name="Collection",
        class_iri="http://www.w3.org/ns/prov#Collection",
        comment="",
    ),
"http://www.w3.org/ns/prov#Communication": AdmittedClass(
        authority_id="prov-o",
        class_name="Communication",
        class_iri="http://www.w3.org/ns/prov#Communication",
        comment="An instance of prov:Communication provides additional descriptions about the binary prov:wasInformedBy relation from an informed prov:Activity to the prov:Activity that informed it. For example, :you_jumping_off_bridge prov:wasInformedBy :everyone_else_jumping_off_bridge; prov:qualifiedCommunication [ a prov:Communication; prov:activity :everyone_else_jumping_off_bridge; :foo :bar ].",
    ),
"http://www.w3.org/ns/prov#Delegation": AdmittedClass(
        authority_id="prov-o",
        class_name="Delegation",
        class_iri="http://www.w3.org/ns/prov#Delegation",
        comment="An instance of prov:Delegation provides additional descriptions about the binary prov:actedOnBehalfOf relation from a performing prov:Agent to some prov:Agent for whom it was performed. For example, :mixing prov:wasAssociatedWith :toddler . :toddler prov:actedOnBehalfOf :mother; prov:qualifiedDelegation [ a prov:Delegation; prov:entity :mother; :foo :bar ].",
    ),
"http://www.w3.org/ns/prov#Derivation": AdmittedClass(
        authority_id="prov-o",
        class_name="Derivation",
        class_iri="http://www.w3.org/ns/prov#Derivation",
        comment="The more specific forms of prov:Derivation (i.e., prov:Revision, prov:Quotation, prov:PrimarySource) should be asserted if they apply.",
    ),
"http://www.w3.org/ns/prov#Derivation": AdmittedClass(
        authority_id="prov-o",
        class_name="Derivation",
        class_iri="http://www.w3.org/ns/prov#Derivation",
        comment="An instance of prov:Derivation provides additional descriptions about the binary prov:wasDerivedFrom relation from some derived prov:Entity to another prov:Entity from which it was derived. For example, :chewed_bubble_gum prov:wasDerivedFrom :unwrapped_bubble_gum; prov:qualifiedDerivation [ a prov:Derivation; prov:entity :unwrapped_bubble_gum; :foo :bar ].",
    ),
"http://www.w3.org/ns/prov#EmptyCollection": AdmittedClass(
        authority_id="prov-o",
        class_name="EmptyCollection",
        class_iri="http://www.w3.org/ns/prov#EmptyCollection",
        comment="",
    ),
"http://www.w3.org/ns/prov#End": AdmittedClass(
        authority_id="prov-o",
        class_name="End",
        class_iri="http://www.w3.org/ns/prov#End",
        comment="An instance of prov:End provides additional descriptions about the binary prov:wasEndedBy relation from some ended prov:Activity to an prov:Entity that ended it. For example, :ball_game prov:wasEndedBy :buzzer; prov:qualifiedEnd [ a prov:End; prov:entity :buzzer; :foo :bar; prov:atTime '2012-03-09T08:05:08-05:00'^^xsd:dateTime ].",
    ),
"http://www.w3.org/ns/prov#Entity": AdmittedClass(
        authority_id="prov-o",
        class_name="Entity",
        class_iri="http://www.w3.org/ns/prov#Entity",
        comment="",
    ),
"http://www.w3.org/ns/prov#EntityInfluence": AdmittedClass(
        authority_id="prov-o",
        class_name="EntityInfluence",
        class_iri="http://www.w3.org/ns/prov#EntityInfluence",
        comment="It is not recommended that the type EntityInfluence be asserted without also asserting one of its more specific subclasses.",
    ),
"http://www.w3.org/ns/prov#EntityInfluence": AdmittedClass(
        authority_id="prov-o",
        class_name="EntityInfluence",
        class_iri="http://www.w3.org/ns/prov#EntityInfluence",
        comment="EntityInfluence provides additional descriptions of an Entity's binary influence upon any other kind of resource. Instances of EntityInfluence use the prov:entity property to cite the influencing Entity.",
    ),
"http://www.w3.org/ns/prov#Generation": AdmittedClass(
        authority_id="prov-o",
        class_name="Generation",
        class_iri="http://www.w3.org/ns/prov#Generation",
        comment="An instance of prov:Generation provides additional descriptions about the binary prov:wasGeneratedBy relation from a generated prov:Entity to the prov:Activity that generated it. For example, :cake prov:wasGeneratedBy :baking; prov:qualifiedGeneration [ a prov:Generation; prov:activity :baking; :foo :bar ].",
    ),
"http://www.w3.org/ns/prov#Influence": AdmittedClass(
        authority_id="prov-o",
        class_name="Influence",
        class_iri="http://www.w3.org/ns/prov#Influence",
        comment="Because prov:Influence is a broad relation, its most specific subclasses (e.g. prov:Communication, prov:Delegation, prov:End, prov:Revision, etc.) should be used when applicable.",
    ),
"http://www.w3.org/ns/prov#Influence": AdmittedClass(
        authority_id="prov-o",
        class_name="Influence",
        class_iri="http://www.w3.org/ns/prov#Influence",
        comment="An instance of prov:Influence provides additional descriptions about the binary prov:wasInfluencedBy relation from some influenced Activity, Entity, or Agent to the influencing Activity, Entity, or Agent. For example, :stomach_ache prov:wasInfluencedBy :spoon; prov:qualifiedInfluence [ a prov:Influence; prov:entity :spoon; :foo :bar ] . Because prov:Influence is a broad relation, the more specific relations (Communication, Delegation, End, etc.) should be used when applicable.",
    ),
"http://www.w3.org/ns/prov#InstantaneousEvent": AdmittedClass(
        authority_id="prov-o",
        class_name="InstantaneousEvent",
        class_iri="http://www.w3.org/ns/prov#InstantaneousEvent",
        comment="An instantaneous event, or event for short, happens in the world and marks a change in the world, in its activities and in its entities. The term 'event' is commonly used in process algebra with a similar meaning. Events represent communications or interactions; they are assumed to be atomic and instantaneous.",
    ),
"http://www.w3.org/ns/prov#Invalidation": AdmittedClass(
        authority_id="prov-o",
        class_name="Invalidation",
        class_iri="http://www.w3.org/ns/prov#Invalidation",
        comment="An instance of prov:Invalidation provides additional descriptions about the binary prov:wasInvalidatedBy relation from an invalidated prov:Entity to the prov:Activity that invalidated it. For example, :uncracked_egg prov:wasInvalidatedBy :baking; prov:qualifiedInvalidation [ a prov:Invalidation; prov:activity :baking; :foo :bar ].",
    ),
"http://www.w3.org/ns/prov#Location": AdmittedClass(
        authority_id="prov-o",
        class_name="Location",
        class_iri="http://www.w3.org/ns/prov#Location",
        comment="",
    ),
"http://www.w3.org/ns/prov#Organization": AdmittedClass(
        authority_id="prov-o",
        class_name="Organization",
        class_iri="http://www.w3.org/ns/prov#Organization",
        comment="",
    ),
"http://www.w3.org/ns/prov#Person": AdmittedClass(
        authority_id="prov-o",
        class_name="Person",
        class_iri="http://www.w3.org/ns/prov#Person",
        comment="",
    ),
"http://www.w3.org/ns/prov#Plan": AdmittedClass(
        authority_id="prov-o",
        class_name="Plan",
        class_iri="http://www.w3.org/ns/prov#Plan",
        comment="There exist no prescriptive requirement on the nature of plans, their representation, the actions or steps they consist of, or their intended goals. Since plans may evolve over time, it may become necessary to track their provenance, so plans themselves are entities. Representing the plan explicitly in the provenance can be useful for various tasks: for example, to validate the execution as represented in the provenance record, to manage expectation failures, or to provide explanations.",
    ),
"http://www.w3.org/ns/prov#PrimarySource": AdmittedClass(
        authority_id="prov-o",
        class_name="PrimarySource",
        class_iri="http://www.w3.org/ns/prov#PrimarySource",
        comment="An instance of prov:PrimarySource provides additional descriptions about the binary prov:hadPrimarySource relation from some secondary prov:Entity to an earlier, primary prov:Entity. For example, :blog prov:hadPrimarySource :newsArticle; prov:qualifiedPrimarySource [ a prov:PrimarySource; prov:entity :newsArticle; :foo :bar ] .",
    ),
"http://www.w3.org/ns/prov#Quotation": AdmittedClass(
        authority_id="prov-o",
        class_name="Quotation",
        class_iri="http://www.w3.org/ns/prov#Quotation",
        comment="An instance of prov:Quotation provides additional descriptions about the binary prov:wasQuotedFrom relation from some taken prov:Entity from an earlier, larger prov:Entity. For example, :here_is_looking_at_you_kid prov:wasQuotedFrom :casablanca_script; prov:qualifiedQuotation [ a prov:Quotation; prov:entity :casablanca_script; :foo :bar ].",
    ),
"http://www.w3.org/ns/prov#Revision": AdmittedClass(
        authority_id="prov-o",
        class_name="Revision",
        class_iri="http://www.w3.org/ns/prov#Revision",
        comment="An instance of prov:Revision provides additional descriptions about the binary prov:wasRevisionOf relation from some newer prov:Entity to an earlier prov:Entity. For example, :draft_2 prov:wasRevisionOf :draft_1; prov:qualifiedRevision [ a prov:Revision; prov:entity :draft_1; :foo :bar ].",
    ),
"http://www.w3.org/ns/prov#Role": AdmittedClass(
        authority_id="prov-o",
        class_name="Role",
        class_iri="http://www.w3.org/ns/prov#Role",
        comment="",
    ),
"http://www.w3.org/ns/prov#SoftwareAgent": AdmittedClass(
        authority_id="prov-o",
        class_name="SoftwareAgent",
        class_iri="http://www.w3.org/ns/prov#SoftwareAgent",
        comment="",
    ),
"http://www.w3.org/ns/prov#Start": AdmittedClass(
        authority_id="prov-o",
        class_name="Start",
        class_iri="http://www.w3.org/ns/prov#Start",
        comment="An instance of prov:Start provides additional descriptions about the binary prov:wasStartedBy relation from some started prov:Activity to an prov:Entity that started it. For example, :foot_race prov:wasStartedBy :bang; prov:qualifiedStart [ a prov:Start; prov:entity :bang; :foo :bar; prov:atTime '2012-03-09T08:05:08-05:00'^^xsd:dateTime ] .",
    ),
"http://www.w3.org/ns/prov#Usage": AdmittedClass(
        authority_id="prov-o",
        class_name="Usage",
        class_iri="http://www.w3.org/ns/prov#Usage",
        comment="An instance of prov:Usage provides additional descriptions about the binary prov:used relation from some prov:Activity to an prov:Entity that it used. For example, :keynote prov:used :podium; prov:qualifiedUsage [ a prov:Usage; prov:entity :podium; :foo :bar ].",
    ),
"http://www.w3.org/ns/shacl#AbstractResult": AdmittedClass(
        authority_id="shacl",
        class_name="AbstractResult",
        class_iri="http://www.w3.org/ns/shacl#AbstractResult",
        comment="The base class of validation results, typically not instantiated directly.",
    ),
"http://www.w3.org/ns/shacl#ConstraintComponent": AdmittedClass(
        authority_id="shacl",
        class_name="ConstraintComponent",
        class_iri="http://www.w3.org/ns/shacl#ConstraintComponent",
        comment="The class of constraint components.",
    ),
"http://www.w3.org/ns/shacl#Function": AdmittedClass(
        authority_id="shacl",
        class_name="Function",
        class_iri="http://www.w3.org/ns/shacl#Function",
        comment="The class of SHACL functions.",
    ),
"http://www.w3.org/ns/shacl#JSConstraint": AdmittedClass(
        authority_id="shacl",
        class_name="JSConstraint",
        class_iri="http://www.w3.org/ns/shacl#JSConstraint",
        comment="The class of constraints backed by a JavaScript function.",
    ),
"http://www.w3.org/ns/shacl#JSExecutable": AdmittedClass(
        authority_id="shacl",
        class_name="JSExecutable",
        class_iri="http://www.w3.org/ns/shacl#JSExecutable",
        comment="Abstract base class of resources that declare an executable JavaScript.",
    ),
"http://www.w3.org/ns/shacl#JSFunction": AdmittedClass(
        authority_id="shacl",
        class_name="JSFunction",
        class_iri="http://www.w3.org/ns/shacl#JSFunction",
        comment="The class of SHACL functions that execute a JavaScript function when called.",
    ),
"http://www.w3.org/ns/shacl#JSLibrary": AdmittedClass(
        authority_id="shacl",
        class_name="JSLibrary",
        class_iri="http://www.w3.org/ns/shacl#JSLibrary",
        comment="Represents a JavaScript library, typically identified by one or more URLs of files to include.",
    ),
"http://www.w3.org/ns/shacl#JSRule": AdmittedClass(
        authority_id="shacl",
        class_name="JSRule",
        class_iri="http://www.w3.org/ns/shacl#JSRule",
        comment="The class of SHACL rules expressed using JavaScript.",
    ),
"http://www.w3.org/ns/shacl#JSTarget": AdmittedClass(
        authority_id="shacl",
        class_name="JSTarget",
        class_iri="http://www.w3.org/ns/shacl#JSTarget",
        comment="The class of targets that are based on JavaScript functions.",
    ),
"http://www.w3.org/ns/shacl#JSTargetType": AdmittedClass(
        authority_id="shacl",
        class_name="JSTargetType",
        class_iri="http://www.w3.org/ns/shacl#JSTargetType",
        comment="The (meta) class for parameterizable targets that are based on JavaScript functions.",
    ),
"http://www.w3.org/ns/shacl#JSValidator": AdmittedClass(
        authority_id="shacl",
        class_name="JSValidator",
        class_iri="http://www.w3.org/ns/shacl#JSValidator",
        comment="A SHACL validator based on JavaScript. This can be used to declare SHACL constraint components that perform JavaScript-based validation when used.",
    ),
"http://www.w3.org/ns/shacl#NodeKind": AdmittedClass(
        authority_id="shacl",
        class_name="NodeKind",
        class_iri="http://www.w3.org/ns/shacl#NodeKind",
        comment="The class of all node kinds, including sh:BlankNode, sh:IRI, sh:Literal or the combinations of these: sh:BlankNodeOrIRI, sh:BlankNodeOrLiteral, sh:IRIOrLiteral.",
    ),
"http://www.w3.org/ns/shacl#NodeShape": AdmittedClass(
        authority_id="shacl",
        class_name="NodeShape",
        class_iri="http://www.w3.org/ns/shacl#NodeShape",
        comment="A node shape is a shape that specifies constraint that need to be met with respect to focus nodes.",
    ),
"http://www.w3.org/ns/shacl#Parameter": AdmittedClass(
        authority_id="shacl",
        class_name="Parameter",
        class_iri="http://www.w3.org/ns/shacl#Parameter",
        comment="The class of parameter declarations, consisting of a path predicate and (possibly) information about allowed value type, cardinality and other characteristics.",
    ),
"http://www.w3.org/ns/shacl#Parameterizable": AdmittedClass(
        authority_id="shacl",
        class_name="Parameterizable",
        class_iri="http://www.w3.org/ns/shacl#Parameterizable",
        comment="Superclass of components that can take parameters, especially functions and constraint components.",
    ),
"http://www.w3.org/ns/shacl#PrefixDeclaration": AdmittedClass(
        authority_id="shacl",
        class_name="PrefixDeclaration",
        class_iri="http://www.w3.org/ns/shacl#PrefixDeclaration",
        comment="The class of prefix declarations, consisting of pairs of a prefix with a namespace.",
    ),
"http://www.w3.org/ns/shacl#PropertyGroup": AdmittedClass(
        authority_id="shacl",
        class_name="PropertyGroup",
        class_iri="http://www.w3.org/ns/shacl#PropertyGroup",
        comment="Instances of this class represent groups of property shapes that belong together.",
    ),
"http://www.w3.org/ns/shacl#PropertyShape": AdmittedClass(
        authority_id="shacl",
        class_name="PropertyShape",
        class_iri="http://www.w3.org/ns/shacl#PropertyShape",
        comment="A property shape is a shape that specifies constraints on the values of a focus node for a given property or path.",
    ),
"http://www.w3.org/ns/shacl#ResultAnnotation": AdmittedClass(
        authority_id="shacl",
        class_name="ResultAnnotation",
        class_iri="http://www.w3.org/ns/shacl#ResultAnnotation",
        comment="A class of result annotations, which define the rules to derive the values of a given annotation property as extra values for a validation result.",
    ),
"http://www.w3.org/ns/shacl#Rule": AdmittedClass(
        authority_id="shacl",
        class_name="Rule",
        class_iri="http://www.w3.org/ns/shacl#Rule",
        comment="The class of SHACL rules. Never instantiated directly.",
    ),
"http://www.w3.org/ns/shacl#SPARQLAskExecutable": AdmittedClass(
        authority_id="shacl",
        class_name="SPARQLAskExecutable",
        class_iri="http://www.w3.org/ns/shacl#SPARQLAskExecutable",
        comment="The class of SPARQL executables that are based on an ASK query.",
    ),
"http://www.w3.org/ns/shacl#SPARQLAskValidator": AdmittedClass(
        authority_id="shacl",
        class_name="SPARQLAskValidator",
        class_iri="http://www.w3.org/ns/shacl#SPARQLAskValidator",
        comment="The class of validators based on SPARQL ASK queries. The queries are evaluated for each value node and are supposed to return true if the given node conforms.",
    ),
"http://www.w3.org/ns/shacl#SPARQLConstraint": AdmittedClass(
        authority_id="shacl",
        class_name="SPARQLConstraint",
        class_iri="http://www.w3.org/ns/shacl#SPARQLConstraint",
        comment="The class of constraints based on SPARQL SELECT queries.",
    ),
"http://www.w3.org/ns/shacl#SPARQLConstructExecutable": AdmittedClass(
        authority_id="shacl",
        class_name="SPARQLConstructExecutable",
        class_iri="http://www.w3.org/ns/shacl#SPARQLConstructExecutable",
        comment="The class of SPARQL executables that are based on a CONSTRUCT query.",
    ),
"http://www.w3.org/ns/shacl#SPARQLExecutable": AdmittedClass(
        authority_id="shacl",
        class_name="SPARQLExecutable",
        class_iri="http://www.w3.org/ns/shacl#SPARQLExecutable",
        comment="The class of resources that encapsulate a SPARQL query.",
    ),
"http://www.w3.org/ns/shacl#SPARQLFunction": AdmittedClass(
        authority_id="shacl",
        class_name="SPARQLFunction",
        class_iri="http://www.w3.org/ns/shacl#SPARQLFunction",
        comment="A function backed by a SPARQL query - either ASK or SELECT.",
    ),
"http://www.w3.org/ns/shacl#SPARQLRule": AdmittedClass(
        authority_id="shacl",
        class_name="SPARQLRule",
        class_iri="http://www.w3.org/ns/shacl#SPARQLRule",
        comment="The class of SHACL rules based on SPARQL CONSTRUCT queries.",
    ),
"http://www.w3.org/ns/shacl#SPARQLSelectExecutable": AdmittedClass(
        authority_id="shacl",
        class_name="SPARQLSelectExecutable",
        class_iri="http://www.w3.org/ns/shacl#SPARQLSelectExecutable",
        comment="The class of SPARQL executables based on a SELECT query.",
    ),
"http://www.w3.org/ns/shacl#SPARQLSelectValidator": AdmittedClass(
        authority_id="shacl",
        class_name="SPARQLSelectValidator",
        class_iri="http://www.w3.org/ns/shacl#SPARQLSelectValidator",
        comment="The class of validators based on SPARQL SELECT queries. The queries are evaluated for each focus node and are supposed to produce bindings for all focus nodes that do not conform.",
    ),
"http://www.w3.org/ns/shacl#SPARQLTarget": AdmittedClass(
        authority_id="shacl",
        class_name="SPARQLTarget",
        class_iri="http://www.w3.org/ns/shacl#SPARQLTarget",
        comment="The class of targets that are based on SPARQL queries.",
    ),
"http://www.w3.org/ns/shacl#SPARQLTargetType": AdmittedClass(
        authority_id="shacl",
        class_name="SPARQLTargetType",
        class_iri="http://www.w3.org/ns/shacl#SPARQLTargetType",
        comment="The (meta) class for parameterizable targets that are based on SPARQL queries.",
    ),
"http://www.w3.org/ns/shacl#SPARQLUpdateExecutable": AdmittedClass(
        authority_id="shacl",
        class_name="SPARQLUpdateExecutable",
        class_iri="http://www.w3.org/ns/shacl#SPARQLUpdateExecutable",
        comment="The class of SPARQL executables based on a SPARQL UPDATE.",
    ),
"http://www.w3.org/ns/shacl#Severity": AdmittedClass(
        authority_id="shacl",
        class_name="Severity",
        class_iri="http://www.w3.org/ns/shacl#Severity",
        comment="The class of validation result severity levels, including violation and warning levels.",
    ),
"http://www.w3.org/ns/shacl#Shape": AdmittedClass(
        authority_id="shacl",
        class_name="Shape",
        class_iri="http://www.w3.org/ns/shacl#Shape",
        comment="A shape is a collection of constraints that may be targeted for certain nodes.",
    ),
"http://www.w3.org/ns/shacl#Target": AdmittedClass(
        authority_id="shacl",
        class_name="Target",
        class_iri="http://www.w3.org/ns/shacl#Target",
        comment="The base class of targets such as those based on SPARQL queries.",
    ),
"http://www.w3.org/ns/shacl#TargetType": AdmittedClass(
        authority_id="shacl",
        class_name="TargetType",
        class_iri="http://www.w3.org/ns/shacl#TargetType",
        comment="The (meta) class for parameterizable targets.	Instances of this are instantiated as values of the sh:target property.",
    ),
"http://www.w3.org/ns/shacl#TripleRule": AdmittedClass(
        authority_id="shacl",
        class_name="TripleRule",
        class_iri="http://www.w3.org/ns/shacl#TripleRule",
        comment="",
    ),
"http://www.w3.org/ns/shacl#ValidationReport": AdmittedClass(
        authority_id="shacl",
        class_name="ValidationReport",
        class_iri="http://www.w3.org/ns/shacl#ValidationReport",
        comment="The class of SHACL validation reports.",
    ),
"http://www.w3.org/ns/shacl#ValidationResult": AdmittedClass(
        authority_id="shacl",
        class_name="ValidationResult",
        class_iri="http://www.w3.org/ns/shacl#ValidationResult",
        comment="The class of validation results.",
    ),
"http://www.w3.org/ns/shacl#Validator": AdmittedClass(
        authority_id="shacl",
        class_name="Validator",
        class_iri="http://www.w3.org/ns/shacl#Validator",
        comment="The class of validators, which provide instructions on how to process a constraint definition. This class serves as base class for the SPARQL-based validators and other possible implementations.",
    ),
}


def is_admitted(class_iri: str) -> bool:
    """True only if `class_iri` is a real, admitted public-authority class -- never true for
    an invented local class IRI, per the PUBLIC-ONLY ADMISSION policy."""
    return class_iri in ADMITTED_CLASSES


def classify(class_iri: str) -> SourceKind | None:
    """The admitted class's `SourceKind`, or `None` if `class_iri` is not admitted (the
    caller must treat an unadmitted class as `UNSUPPORTED`, never silently invent one)."""
    admitted = ADMITTED_CLASSES.get(class_iri)
    if admitted is None:
        return None
    return PUBLIC_AUTHORITIES[admitted.authority_id].source_kind
