from __future__ import annotations

# Seed families are documentation/discovery data, not an allow-list. The simulator
# intentionally accepts novel service names so new cloud APIs do not require a new
# execution kernel branch.
SERVICE_FAMILIES: dict[str, tuple[str, ...]] = {
    "aws": (
        "iam",
        "organizations",
        "ec2",
        "vpc",
        "elasticloadbalancing",
        "s3",
        "rds",
        "dynamodb",
        "lambda",
        "sqs",
        "sns",
        "kms",
        "secretsmanager",
        "eks",
        "route53",
        "cloudwatch",
        "cloudfront",
        "redshift",
        "glue",
        "sagemaker",
        "backup",
    ),
    "azure": (
        "authorization",
        "managementgroups",
        "compute",
        "network",
        "loadbalancer",
        "storage",
        "sql",
        "cosmosdb",
        "functions",
        "servicebus",
        "eventgrid",
        "keyvault",
        "aks",
        "dns",
        "monitor",
        "frontdoor",
        "synapse",
        "datafactory",
        "machinelearning",
        "recoveryservices",
    ),
    "gcp": (
        "iam",
        "resourcemanager",
        "compute",
        "network",
        "loadbalancing",
        "storage",
        "sqladmin",
        "spanner",
        "run",
        "pubsub",
        "eventarc",
        "kms",
        "secretmanager",
        "gke",
        "dns",
        "monitoring",
        "cloudcdn",
        "bigquery",
        "dataflow",
        "aiplatform",
        "backupdr",
    ),
}


def service_catalog_size() -> int:
    return sum(len(items) for items in SERVICE_FAMILIES.values())
