"""Chicago-style unit smoke test for `ChatmanStateProvider`
(gymact.gyms.chatman_state_gym) -- real materialize/read/teardown against the real
provider, no mocks, state-based assertions on the real returned values.

Hand-maintained, matching the repo's own test convention (confirmed
2026-08-13: no `ggen/` pack targets `tests/gyms/test_*_unit.py`; this file
previously carried a false "GENERATED by ggen" banner from an
architecturally-wrong out-of-tree pack at `~/ggen/packs/gymact-episode-pack/`,
now deleted).
"""

from __future__ import annotations

import pytest
from pathlib import Path

from gymact import GymAct, MaterializationIntent
from gymact.gyms.chatman_state_gym import ChatmanStateProvider


@pytest.mark.asyncio
async def test_chatman_state_materialize_read_teardown() -> None:
    gym = GymAct()
    gym.register_provider(ChatmanStateProvider())

    materialization = await gym.materialize(
        MaterializationIntent(
            provider="chatman-state",
            scenario=None,
            config={"repo_limit": 10},
        )
    )
    assert materialization.accepted, materialization.receipt.reason
    assert materialization.episode is not None
    episode_id = materialization.episode.episode_id

    try:

        result_1 = await gym.read(
            episode_id,
            f"urn:gymact:chatman-state:capability:list_local_repos",
            {},
        )
        assert "result" in result_1

        result_2 = await gym.read(
            episode_id,
            f"urn:gymact:chatman-state:capability:list_github_repos",
            {},
        )
        assert "result" in result_2

        result_3 = await gym.read(
            episode_id,
            f"urn:gymact:chatman-state:capability:portfolio_summary",
            {},
        )
        assert "result" in result_3

        result_4 = await gym.read(
            episode_id,
            f"urn:gymact:chatman-state:capability:estimated_effort_cost",
            {"repo": str(Path.home() / "gymact"), "since": "30 days ago"},
        )
        assert "result" in result_4


        verification = await gym.verify(episode_id, {"repo_limit": 10})
        assert verification.passed, verification.observation
    finally:
        teardown_receipt = await gym.teardown(episode_id)
        assert teardown_receipt.standing.value == "ALIVE"
