"""Chicago-style unit smoke test for `CloudTopologyProvider`
(gymact.gyms.cloud_topology_gym) -- real materialize/read/teardown against the real
provider, no mocks, state-based assertions on the real returned values.

Hand-maintained, matching the repo's own test convention (confirmed
2026-08-13: no `ggen/` pack targets `tests/gyms/test_*_unit.py`; this file
previously carried a false "GENERATED by ggen" banner from an
architecturally-wrong out-of-tree pack at `~/ggen/packs/gymact-episode-pack/`,
now deleted).
"""

from __future__ import annotations

import pytest
from pathlib import Path

from gymact import GymAct, MaterializationIntent
from gymact.gyms.cloud_topology_gym import CloudTopologyProvider


@pytest.mark.asyncio
async def test_cloud_topology_materialize_read_teardown() -> None:
    gym = GymAct()
    gym.register_provider(CloudTopologyProvider())

    materialization = await gym.materialize(
        MaterializationIntent(
            provider="cloud-topology",
            scenario="aws",
            config={"provider": "aws"},
        )
    )
    assert materialization.accepted, materialization.receipt.reason
    assert materialization.episode is not None
    episode_id = materialization.episode.episode_id

    try:

        result_1 = await gym.read(
            episode_id,
            f"urn:gymact:cloud-topology:capability:list_regions",
            {},
        )
        assert "result" in result_1

        result_2 = await gym.read(
            episode_id,
            f"urn:gymact:cloud-topology:capability:list_services",
            {},
        )
        assert "result" in result_2

        result_3 = await gym.read(
            episode_id,
            f"urn:gymact:cloud-topology:capability:services_in_region",
            {"region": "us-east-1"},
        )
        assert "result" in result_3

        result_4 = await gym.read(
            episode_id,
            f"urn:gymact:cloud-topology:capability:validate_topology",
            {},
        )
        assert "result" in result_4

        result_5 = await gym.read(
            episode_id,
            f"urn:gymact:cloud-topology:capability:estimated_managed_k8s_cost",
            {},
        )
        assert "result" in result_5


        verification = await gym.verify(episode_id, {"provider": "aws", "validated": True})
        assert verification.passed, verification.observation
    finally:
        teardown_receipt = await gym.teardown(episode_id)
        assert teardown_receipt.standing.value == "ALIVE"
