from enum import StrEnum


class Refusal(StrEnum):
    INVALID_SUBJECT = "INVALID_SUBJECT"
    SUBJECT_DRIFT = "SUBJECT_DRIFT"
    SOLVER_DIVERGENCE = "SOLVER_DIVERGENCE"
    DUAL_DIVERGENCE = "DUAL_DIVERGENCE"
    ORACLE_DIVERGENCE = "ORACLE_DIVERGENCE"
    NONZERO_DUALITY_GAP = "NONZERO_DUALITY_GAP"
    NONINDEPENDENT_ENGINE = "NONINDEPENDENT_ENGINE"
    RUNTIME_MISMATCH = "RUNTIME_MISMATCH"
    METHOD_MISMATCH = "METHOD_MISMATCH"
    STALE_CERTIFICATE = "STALE_CERTIFICATE"
    UNRECEIPTED_ACTUATION = "UNRECEIPTED_ACTUATION"
    RECEIPT_DRIFT = "RECEIPT_DRIFT"
