#!/usr/bin/env python3
"""Run one real GymAct episode over `CloudTopologyProvider` and write a
real OCEL 2.0 log at reports/ocel/cloud-topology/episode.ocel.json.

Hand-maintained, matching every other `scripts/run_*_episode.py` in this
repo (per `~/gymact/CLAUDE.md`'s "Python vs Rust/ggen" law: "Do not generate
Python boilerplate with ggen when the host ecosystem already derives the
surface correctly from Python types" -- confirmed 2026-08-13 that all 15
other episode scripts in this directory are hand-written, none generated,
and no pack in `ggen/` targets `scripts/run_*_episode.py` or
`tests/gyms/test_*_unit.py`; this file previously carried a false
"GENERATED by ggen" banner from an architecturally-wrong out-of-tree pack
at `~/ggen/packs/gymact-episode-pack/`, now deleted -- see that pack's
former README for the adversarial-review rationale).

Mirrors `scripts/run_dev_portfolio_episode.py`'s real read-only shape
(materialize -> read (per capability, via `GymAct.read()`, the real
Consequence.READ counterpart of `act()`) -> verify -> teardown ->
write_ocel_log), generalized across every READ-only gym this pack targets.

Usage:
    uv run python scripts/run_cloud_topology_episode.py
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from gymact import GymAct, MaterializationIntent
from gymact.gyms.cloud_topology_gym import CloudTopologyProvider
from gymact.models import Operation
from gymact.ocel import write_ocel_log

REPORTS_DIR = Path(__file__).parent.parent / "reports" / "ocel"

GYM_URN_NAME = "cloud-topology"


async def run() -> None:
    provider = CloudTopologyProvider()
    gym = GymAct()
    gym.register_provider(provider)
    receipts = []
    log_path = REPORTS_DIR / "cloud-topology" / "episode.ocel.json"

    materialization = await gym.materialize(
        MaterializationIntent(
            provider="cloud-topology",
            scenario="aws",
            config={"provider": "aws"},
        )
    )
    receipts.append(materialization.receipt)
    if not materialization.accepted or materialization.episode is None:
        print(f"cloud_topology: materialization refused: {materialization.receipt.reason}")
        log, digest = write_ocel_log(log_path, receipts)
        print(f"cloud_topology: {len(log['events'])} events, sha256={digest}")
        return

    episode_id = materialization.episode.episode_id

    # Each read call below invokes `GymAct.read()` -- the real, symmetric
    # READ-only counterpart of `act()` (kernel.py's `READ_CAPABILITY_IS_NOT_ACTUATION`
    # / `DO_CAPABILITY_IS_NOT_A_READ` refusal pair) -- no Receipt/authority
    # path runs for a real READ capability, so each call result is recorded
    # as its own derived OCEL event (same technique
    # `run_dev_portfolio_episode.py` already established: copy the
    # materialize receipt for shared episode/subject identity, override
    # `operation` to OBSERVE, drop the materialize-only idempotency_key).

    result_1 = await gym.read(
        episode_id,
        f"urn:gymact:{GYM_URN_NAME}:capability:list_regions",
        {},
    )
    print(f"cloud_topology: list_regions -> {result_1['result']!r:.200}")
    receipts.append(
        materialization.receipt.model_copy(
            update={
                "operation": Operation.OBSERVE,
                "idempotency_key": None,
                "reason": f"read list_regions: {str(result_1['result'])[:180]}",
            }
        )
    )

    result_2 = await gym.read(
        episode_id,
        f"urn:gymact:{GYM_URN_NAME}:capability:list_services",
        {},
    )
    print(f"cloud_topology: list_services -> {result_2['result']!r:.200}")
    receipts.append(
        materialization.receipt.model_copy(
            update={
                "operation": Operation.OBSERVE,
                "idempotency_key": None,
                "reason": f"read list_services: {str(result_2['result'])[:180]}",
            }
        )
    )

    result_3 = await gym.read(
        episode_id,
        f"urn:gymact:{GYM_URN_NAME}:capability:services_in_region",
        {"region": "us-east-1"},
    )
    print(f"cloud_topology: services_in_region -> {result_3['result']!r:.200}")
    receipts.append(
        materialization.receipt.model_copy(
            update={
                "operation": Operation.OBSERVE,
                "idempotency_key": None,
                "reason": f"read services_in_region: {str(result_3['result'])[:180]}",
            }
        )
    )

    result_4 = await gym.read(
        episode_id,
        f"urn:gymact:{GYM_URN_NAME}:capability:validate_topology",
        {},
    )
    print(f"cloud_topology: validate_topology -> {result_4['result']!r:.200}")
    receipts.append(
        materialization.receipt.model_copy(
            update={
                "operation": Operation.OBSERVE,
                "idempotency_key": None,
                "reason": f"read validate_topology: {str(result_4['result'])[:180]}",
            }
        )
    )

    result_5 = await gym.read(
        episode_id,
        f"urn:gymact:{GYM_URN_NAME}:capability:estimated_managed_k8s_cost",
        {},
    )
    print(f"cloud_topology: estimated_managed_k8s_cost -> {result_5['result']!r:.200}")
    receipts.append(
        materialization.receipt.model_copy(
            update={
                "operation": Operation.OBSERVE,
                "idempotency_key": None,
                "reason": f"read estimated_managed_k8s_cost: {str(result_5['result'])[:180]}",
            }
        )
    )


    verification = await gym.verify(episode_id, {"provider": "aws", "validated": True})
    print(f"cloud_topology: verify_passed={verification.passed}")

    receipts.append(await gym.teardown(episode_id))

    log, digest = write_ocel_log(log_path, receipts)
    print(f"cloud_topology: {len(log['events'])} events, sha256={digest}")


if __name__ == "__main__":
    asyncio.run(run())
