#!/usr/bin/env python3
"""Run one real GymAct episode over `ChatmanStateProvider` and write a
real OCEL 2.0 log at reports/ocel/chatman-state/episode.ocel.json.

Hand-maintained, matching every other `scripts/run_*_episode.py` in this
repo (per `~/gymact/CLAUDE.md`'s "Python vs Rust/ggen" law: "Do not generate
Python boilerplate with ggen when the host ecosystem already derives the
surface correctly from Python types" -- confirmed 2026-08-13 that all 15
other episode scripts in this directory are hand-written, none generated,
and no pack in `ggen/` targets `scripts/run_*_episode.py` or
`tests/gyms/test_*_unit.py`; this file previously carried a false
"GENERATED by ggen" banner from an architecturally-wrong out-of-tree pack
at `~/ggen/packs/gymact-episode-pack/`, now deleted -- see that pack's
former README for the adversarial-review rationale).

Mirrors `scripts/run_dev_portfolio_episode.py`'s real read-only shape
(materialize -> read (per capability, via `GymAct.read()`, the real
Consequence.READ counterpart of `act()`) -> verify -> teardown ->
write_ocel_log), generalized across every READ-only gym this pack targets.

Usage:
    uv run python scripts/run_chatman_state_episode.py
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from gymact import GymAct, MaterializationIntent
from gymact.gyms.chatman_state_gym import ChatmanStateProvider
from gymact.models import Operation
from gymact.ocel import write_ocel_log

REPORTS_DIR = Path(__file__).parent.parent / "reports" / "ocel"

GYM_URN_NAME = "chatman-state"


async def run() -> None:
    provider = ChatmanStateProvider()
    gym = GymAct()
    gym.register_provider(provider)
    receipts = []
    log_path = REPORTS_DIR / "chatman-state" / "episode.ocel.json"

    materialization = await gym.materialize(
        MaterializationIntent(
            provider="chatman-state",
            scenario=None,
            config={"repo_limit": 10},
        )
    )
    receipts.append(materialization.receipt)
    if not materialization.accepted or materialization.episode is None:
        print(f"chatman_state: materialization refused: {materialization.receipt.reason}")
        log, digest = write_ocel_log(log_path, receipts)
        print(f"chatman_state: {len(log['events'])} events, sha256={digest}")
        return

    episode_id = materialization.episode.episode_id

    # Each read call below invokes `GymAct.read()` -- the real, symmetric
    # READ-only counterpart of `act()` (kernel.py's `READ_CAPABILITY_IS_NOT_ACTUATION`
    # / `DO_CAPABILITY_IS_NOT_A_READ` refusal pair) -- no Receipt/authority
    # path runs for a real READ capability, so each call result is recorded
    # as its own derived OCEL event (same technique
    # `run_dev_portfolio_episode.py` already established: copy the
    # materialize receipt for shared episode/subject identity, override
    # `operation` to OBSERVE, drop the materialize-only idempotency_key).

    result_1 = await gym.read(
        episode_id,
        f"urn:gymact:{GYM_URN_NAME}:capability:list_local_repos",
        {},
    )
    print(f"chatman_state: list_local_repos -> {result_1['result']!r:.200}")
    receipts.append(
        materialization.receipt.model_copy(
            update={
                "operation": Operation.OBSERVE,
                "idempotency_key": None,
                "reason": f"read list_local_repos: {str(result_1['result'])[:180]}",
            }
        )
    )

    result_2 = await gym.read(
        episode_id,
        f"urn:gymact:{GYM_URN_NAME}:capability:list_github_repos",
        {},
    )
    print(f"chatman_state: list_github_repos -> {result_2['result']!r:.200}")
    receipts.append(
        materialization.receipt.model_copy(
            update={
                "operation": Operation.OBSERVE,
                "idempotency_key": None,
                "reason": f"read list_github_repos: {str(result_2['result'])[:180]}",
            }
        )
    )

    result_3 = await gym.read(
        episode_id,
        f"urn:gymact:{GYM_URN_NAME}:capability:portfolio_summary",
        {},
    )
    print(f"chatman_state: portfolio_summary -> {result_3['result']!r:.200}")
    receipts.append(
        materialization.receipt.model_copy(
            update={
                "operation": Operation.OBSERVE,
                "idempotency_key": None,
                "reason": f"read portfolio_summary: {str(result_3['result'])[:180]}",
            }
        )
    )

    result_4 = await gym.read(
        episode_id,
        f"urn:gymact:{GYM_URN_NAME}:capability:estimated_effort_cost",
        {"repo": str(Path.home() / "gymact"), "since": "30 days ago"},
    )
    print(f"chatman_state: estimated_effort_cost -> {result_4['result']!r:.200}")
    receipts.append(
        materialization.receipt.model_copy(
            update={
                "operation": Operation.OBSERVE,
                "idempotency_key": None,
                "reason": f"read estimated_effort_cost: {str(result_4['result'])[:180]}",
            }
        )
    )


    verification = await gym.verify(episode_id, {"repo_limit": 10})
    print(f"chatman_state: verify_passed={verification.passed}")

    receipts.append(await gym.teardown(episode_id))

    log, digest = write_ocel_log(log_path, receipts)
    print(f"chatman_state: {len(log['events'])} events, sha256={digest}")


if __name__ == "__main__":
    asyncio.run(run())
