#!/usr/bin/env python3
"""Real CLI: print each real provider's independent `ValidationResult` and exit non-zero if
any provider is invalid.

GENERATED by ggen from ggen/cloud-topology-validation-pack/ontology.ttl -- do not hand-edit;
the provider list below is echoed from the same ontology
`cloud_topology_validation.py.tmpl` renders, so this script can never enumerate a different
set of providers than the validator actually implements.
"""

from __future__ import annotations

import sys

from gymact.gyms.cloud_topology_validation import validate_all_topologies


def main() -> int:
    results = validate_all_topologies()
    any_invalid = False
    for provider in ("aws", "azure", "gcp"):
        r = results[provider]
        status = "VALID" if r.valid else "INVALID"
        print(f"{provider}: {status} stale={r.stale} stale_reasons={r.stale_reasons}")
        print(
            f"  loaded={r.loaded_region_count}r/{r.loaded_service_count}s "
            f"independent={r.independent_region_count}r/{r.independent_service_count}s"
        )
        if r.problems:
            for problem in r.problems:
                print(f"  problem: {problem}")
            any_invalid = True
    return 1 if any_invalid else 0


if __name__ == "__main__":
    raise SystemExit(main())
