"""GymAct public API."""

from gymact.action_contract import (
    ActionDefinition,
    AdmissionResult,
    AuthorityRequirement,
    ExecutionGrant,
    ExpectedEffect,
    IdempotencyClass,
    ObservationConfidence,
    PreparedAction,
    ProviderHealth,
    ProviderMetadata,
    ReconciliationDisposition,
    ReconciliationResult,
    RefusalCode,
    ReversalClass,
    SubjectRef,
    VerificationKind,
    VerificationStrategy,
    admit_execution,
    admit_retry,
    construct_prepared_action,
)
from gymact.authority import AllowListAuthorityResolver, AuthorityResolver, DenyAuthorityResolver
from gymact.brce import BRCEBroker, BrokerRequest
from gymact.capsule import (
    CapsuleIdentity,
    CapsuleReuseDecision,
    SubjectCapsuleReceipt,
    ValidationPack,
    VerifierCapsuleReceipt,
    evaluate_capsule_reuse,
)
from gymact.compileout import (
    CompiledRecipe,
    RecipeAdmission,
    RecipeCache,
    RecipeIdentity,
    admit_compiled_recipe,
    compile_recipe,
)
from gymact.contract import RuntimeContract, build_contract
from gymact.crown_runtime import (
    ReconciledTransition,
    VerifiedTransition,
    execute_admitted,
    execute_verified,
    reconcile_uncertain,
)
from gymact.decision_cache import (
    CandidateDecision,
    DecisionCache,
    DecisionKey,
    DecisionResolution,
    RefusalDecision,
)
from gymact.errc import ERRCItem, ERRCMove, ERRCStatus, ERRCSummary, errc_summary, load_errc
from gymact.evidence import EvidenceRecord, MemoryReceiptLedger, ReceiptLedger, evidence_graph
from gymact.experiments import (
    AntiAgentPoint,
    AntiAgentReport,
    CompileOutReport,
    FaultInjector,
    FaultKind,
    FaultPlan,
    IntelligenceRun,
    SelfPlayCase,
    SelfPlayReport,
    TransitionEconomics,
    anti_agent_benchmark,
    evaluate_compile_out,
    run_self_play,
)
from gymact.intelligence import (
    CognitionEpisode,
    CompilationCandidate,
    CompileOutObservation,
    IntelligenceRegime,
    SelectionDecision,
    detect_compilation_candidate,
    route_intelligence,
)
from gymact.lab import (
    ActionProjection,
    CapabilityCache,
    CapabilityCacheEntry,
    CostPoint,
    CrossoverResult,
    DifferentialVerdict,
    EdgeControllerManifest,
    EmpiricalProviderIndex,
    ForwardBenchSubject,
    ProblemSignature,
    ProjectionKind,
    ProviderBenchmarkRecord,
    ProviderFamily,
    SelfPlayKind,
    SelfPlayScenario,
    TransitionMetrics,
    VCTObservation,
    differential_verdict,
    find_crossover,
    manufacture_self_play,
    pareto_frontier,
    project_action,
)
from gymact.limits import RuntimeLimits
from gymact.local_providers import FilesystemProvider, GitProvider, SQLiteProvider
from gymact.manufacture import export_manufacturing_bundle
from gymact.models import (
    ActuationIntent,
    ActuationResult,
    AuthorityDecision,
    AuthorityRequest,
    Capability,
    Consequence,
    Episode,
    MaterializationIntent,
    MaterializationResult,
    Observation,
    Operation,
    Receipt,
    Score,
    Standing,
    VerificationResult,
)
from gymact.network_providers import HTTPJSONProvider
from gymact.oracle import (
    DifferentialVerification,
    OracleObservation,
    differential_verify,
    observe_oracle,
)
from gymact.physical import (
    ControllerMode,
    EdgeControllerArtifact,
    PhysicalAdmission,
    PhysicalCommand,
    PhysicalDomain,
    PhysicalProviderProfile,
    RiskClass,
    SafetyEnvelope,
    admit_physical_command,
)
from gymact.plugins import (
    ProviderPluginInfo,
    ProviderPluginLoad,
    discover_provider_plugins,
    load_provider_plugin,
)
from gymact.provider_spi import (
    CrownProvider,
    ObservationRequest,
    ProviderExecutionAttempt,
    ProviderPreparation,
    ProviderRollbackResult,
)
from gymact.providers import Environment, EnvironmentProvider, MemoryProvider
from gymact.registry import (
    builtin_capabilities,
    builtin_provider_names,
    create_builtin_provider,
    describe_builtin_provider,
)
from gymact.replay import ReplayExpectation, ReplayMode, ReplayReport, replay_ledger
from gymact.requirements import CrownSummary, crown_summary, load_crown_requirements
from gymact.runtime import BoundaryBlocked, GymAct, ProductionGymAct
from gymact.scoring import BinaryVerificationScorer, Scorer, score_verification
from gymact.semantic import ProfileAuthority, SemanticValidation
from gymact.sqlite_ledger import SQLiteReceiptLedger
from gymact.transport import (
    CandidateIntentEnvelope,
    TransportKind,
    normalize_candidate,
    protocol_equivalent,
)

__all__ = [
    "ActionDefinition",
    "ActionProjection",
    "ActuationIntent",
    "ActuationResult",
    "AdmissionResult",
    "AllowListAuthorityResolver",
    "AntiAgentPoint",
    "AntiAgentReport",
    "AuthorityDecision",
    "AuthorityRequest",
    "AuthorityRequirement",
    "AuthorityResolver",
    "BRCEBroker",
    "BinaryVerificationScorer",
    "BoundaryBlocked",
    "BrokerRequest",
    "CandidateDecision",
    "CandidateIntentEnvelope",
    "Capability",
    "CapabilityCache",
    "CapabilityCacheEntry",
    "CapsuleIdentity",
    "CapsuleReuseDecision",
    "CognitionEpisode",
    "CompilationCandidate",
    "CompileOutObservation",
    "CompileOutReport",
    "CompiledRecipe",
    "Consequence",
    "ControllerMode",
    "CostPoint",
    "CrossoverResult",
    "CrownProvider",
    "CrownSummary",
    "DecisionCache",
    "DecisionKey",
    "DecisionResolution",
    "DenyAuthorityResolver",
    "DifferentialVerdict",
    "DifferentialVerification",
    "ERRCItem",
    "ERRCMove",
    "ERRCStatus",
    "ERRCSummary",
    "EdgeControllerArtifact",
    "EdgeControllerManifest",
    "EmpiricalProviderIndex",
    "Environment",
    "EnvironmentProvider",
    "Episode",
    "EvidenceRecord",
    "ExecutionGrant",
    "ExpectedEffect",
    "FaultInjector",
    "FaultKind",
    "FaultPlan",
    "FilesystemProvider",
    "ForwardBenchSubject",
    "GitProvider",
    "GymAct",
    "HTTPJSONProvider",
    "IdempotencyClass",
    "IntelligenceRegime",
    "IntelligenceRun",
    "MaterializationIntent",
    "MaterializationResult",
    "MemoryProvider",
    "MemoryReceiptLedger",
    "Observation",
    "ObservationConfidence",
    "ObservationRequest",
    "Operation",
    "OracleObservation",
    "PhysicalAdmission",
    "PhysicalCommand",
    "PhysicalDomain",
    "PhysicalProviderProfile",
    "PreparedAction",
    "ProblemSignature",
    "ProductionGymAct",
    "ProfileAuthority",
    "ProjectionKind",
    "ProviderBenchmarkRecord",
    "ProviderExecutionAttempt",
    "ProviderFamily",
    "ProviderHealth",
    "ProviderMetadata",
    "ProviderPluginInfo",
    "ProviderPluginLoad",
    "ProviderPreparation",
    "ProviderRollbackResult",
    "Receipt",
    "ReceiptLedger",
    "RecipeAdmission",
    "RecipeCache",
    "RecipeIdentity",
    "ReconciledTransition",
    "ReconciliationDisposition",
    "ReconciliationResult",
    "RefusalCode",
    "RefusalDecision",
    "ReplayExpectation",
    "ReplayMode",
    "ReplayReport",
    "ReversalClass",
    "RiskClass",
    "RuntimeContract",
    "RuntimeLimits",
    "SQLiteProvider",
    "SQLiteReceiptLedger",
    "SafetyEnvelope",
    "Score",
    "Scorer",
    "SelectionDecision",
    "SelfPlayCase",
    "SelfPlayKind",
    "SelfPlayReport",
    "SelfPlayScenario",
    "SemanticValidation",
    "Standing",
    "SubjectCapsuleReceipt",
    "SubjectRef",
    "TransitionEconomics",
    "TransitionMetrics",
    "TransportKind",
    "VCTObservation",
    "ValidationPack",
    "VerificationKind",
    "VerificationResult",
    "VerificationStrategy",
    "VerifiedTransition",
    "VerifierCapsuleReceipt",
    "admit_compiled_recipe",
    "admit_execution",
    "admit_physical_command",
    "admit_retry",
    "anti_agent_benchmark",
    "build_contract",
    "builtin_capabilities",
    "builtin_provider_names",
    "compile_recipe",
    "construct_prepared_action",
    "create_builtin_provider",
    "crown_summary",
    "describe_builtin_provider",
    "detect_compilation_candidate",
    "differential_verdict",
    "differential_verify",
    "discover_provider_plugins",
    "errc_summary",
    "evaluate_capsule_reuse",
    "evidence_graph",
    "evaluate_compile_out",
    "execute_admitted",
    "execute_verified",
    "export_manufacturing_bundle",
    "find_crossover",
    "load_crown_requirements",
    "load_errc",
    "load_provider_plugin",
    "manufacture_self_play",
    "normalize_candidate",
    "observe_oracle",
    "pareto_frontier",
    "project_action",
    "protocol_equivalent",
    "reconcile_uncertain",
    "replay_ledger",
    "route_intelligence",
    "run_self_play",
    "score_verification",
]

__version__ = "26.8.7"
