"""Built-in provider registry; semantic capability identity stays shared across transports.

GENERATED by ggen from ggen/gymact-registry-pack/ontology.ttl -- do not hand-edit. Adding a
new gym provider means adding an rg:RegisteredProvider individual to that ontology, not
editing this file's import block or `_BUILTINS` dict directly -- the generator cannot
"forget" a registration the way hand-editing two separate files (a new gym module plus this
dict) once did (see tests/test_registry_completeness_chicago.py's own docstring for the real
gap this closes: CloudTopologyProvider shipped without ever being registered here).

`_OUTCOME_PREDICATES` is the opt-in structured-outcome counterpart: most providers declare
neither rg:outcomePredicateModule nor rg:outcomePredicateExpr, so this dict is empty for them
and scripts/ocel_standing.py keeps using its generic solved=True substring fallback -- see
that ontology property's rdfs:comment for the opt-in contract.
"""

from __future__ import annotations

from typing import Any, Callable

from gymact.gyms.chatman_state_gym import CHATMAN_STATE_CAPABILITIES, ChatmanStateProvider
from gymact.gyms.cloud_topology_gym import CLOUD_TOPOLOGY_CAPABILITIES, CloudTopologyProvider
from gymact.gyms.cloudsim import CLOUDSIM_CAPABILITIES, CloudSimProvider
from gymact.gyms.codebase import CODEBASE_CAPABILITIES, CodebaseProvider
from gymact.gyms.commerce_dfcm_gym import COMMERCE_DFCM_CAPABILITIES, CommerceDfcmProvider
from gymact.gyms.dev_portfolio import DEV_PORTFOLIO_CAPABILITIES, DevPortfolioProvider
from gymact.gyms.discovered import DISCOVERED_RUN_CAPABILITY, GenericDiscoveredProvider
from gymact.gyms.enterprise_company import (
    ENTERPRISE_COMPANY_CAPABILITIES,
    EnterpriseCompanyProvider,
)
from gymact.gyms.ggen import GGEN_CAPABILITIES, GgenProvider
from gymact.gyms.ggen_legacy import GGEN_LEGACY_CAPABILITIES, GgenLegacyVerifierProvider
from gymact.gyms.k8s_resource_gym import K8S_RESOURCE_CAPABILITIES, K8sResourceProvider
from gymact.gyms.kubernetes_reconciliation import (
    KUBERNETES_RECONCILIATION_CAPABILITIES,
    KubernetesReconciliationProvider,
)
from gymact.gyms.lock_and_key import LOCK_AND_KEY_CAPABILITIES, LockAndKeyProvider
from gymact.gyms.mcp_client_session import (
    MCP_CALL_TOOL_CAPABILITY,
    MCP_LIST_TOOLS_CAPABILITY,
    McpClientSessionProvider,
)
from gymact.gyms.multicloud import (
    CAPABILITY_REGISTRY as MULTICLOUD_CAPABILITIES,
)
from gymact.gyms.multicloud import (
    MulticloudProvider,
)
from gymact.gyms.platform_console_provider import (
    PLATFORM_CONSOLE_CAPABILITIES,
    PlatformConsoleProvider,
)
from gymact.gyms.resource_flow import RESOURCE_FLOW_CAPABILITIES, ResourceFlowProvider
from gymact.gyms.sregym_ontology import SREGYM_CAPABILITIES, SregymOntologyProvider
from gymact.gyms.swegym import SWEGYM_EVALUATE_CAPABILITY, SWEGymProvider
from gymact.gyms.switchboard import SWITCHBOARD_CAPABILITIES, SwitchboardProvider
from gymact.gyms.terraform_docker_apply import (
    TERRAFORM_DOCKER_APPLY_CAPABILITIES,
    TerraformDockerApplyProvider,
)
from gymact.gyms.terraform_plan import TERRAFORM_PLAN_CAPABILITIES, TerraformPlanProvider
from gymact.local_providers import (
    FILESYSTEM_CAPABILITIES,
    GIT_CAPABILITIES,
    SQLITE_CAPABILITIES,
    FilesystemProvider,
    GitProvider,
    SQLiteProvider,
)
from gymact.network_providers import HTTP_JSON_CAPABILITIES, HTTPJSONProvider
from gymact.providers import MEMORY_CAPABILITIES, MemoryProvider


# NOT registered here (deliberately, not an oversight):
#   - gymact.gyms.browsergym.BrowserGymProvider: top-level `import browsergym.core` / `import gymnasium`, both gated behind the optional "gyms" extra -- importing this module with only the base install raises ImportError, so registering it would break a clean `import gymact.registry`.
#   - gymact.gyms.cube_container_counter.CubeContainerCounterProvider: top-level `from cube.infra_local import LocalInfraConfig` wrapped in try/except that re-raises ImportError, gated behind the optional "cube" extra with Docker.
#   - gymact.gyms.cube_counter.CubeCounterProvider: top-level `from counter_cube...` wrapped in try/except that re-raises ImportError, gated behind the optional "cube" extra (cube-standard/counter-cube, Python >=3.12 only).
#   - gymact.gyms.gymnasium_env.GymnasiumProvider: top-level `import gymnasium`, same optional "gyms" extra gate as browsergym.py above.
#   - gymact.gyms.inspect_evals.InspectEvalsProvider: top-level `from inspect_ai import ...`, gated behind the optional "gyms" extra (inspect-ai).
#   - gymact.gyms.vendor_benchmarks.VendorBenchmarkProvider: generic vendor-benchmark dispatch surface, not a single fixed-capability gym -- registered per-vendor benchmark target elsewhere, not as one flat builtin name here.

_BUILTINS = {
    "chatman-state": (ChatmanStateProvider, CHATMAN_STATE_CAPABILITIES),
    "cloud-topology": (CloudTopologyProvider, CLOUD_TOPOLOGY_CAPABILITIES),
    "cloudsim": (CloudSimProvider, CLOUDSIM_CAPABILITIES),
    "codebase": (CodebaseProvider, CODEBASE_CAPABILITIES),
    "commerce-dfcm": (CommerceDfcmProvider, COMMERCE_DFCM_CAPABILITIES),
    "dev-portfolio": (DevPortfolioProvider, DEV_PORTFOLIO_CAPABILITIES),
    "discovered": (GenericDiscoveredProvider, (DISCOVERED_RUN_CAPABILITY,)),
    "enterprise-company": (EnterpriseCompanyProvider, ENTERPRISE_COMPANY_CAPABILITIES),
    "filesystem": (FilesystemProvider, FILESYSTEM_CAPABILITIES),
    "ggen": (GgenProvider, GGEN_CAPABILITIES),
    "ggen-legacy": (GgenLegacyVerifierProvider, GGEN_LEGACY_CAPABILITIES),
    "git": (GitProvider, GIT_CAPABILITIES),
    "http-json": (HTTPJSONProvider, HTTP_JSON_CAPABILITIES),
    "k8s-resource": (K8sResourceProvider, K8S_RESOURCE_CAPABILITIES),
    "kubernetes-reconciliation": (
        KubernetesReconciliationProvider,
        KUBERNETES_RECONCILIATION_CAPABILITIES,
    ),
    "lock-and-key": (LockAndKeyProvider, LOCK_AND_KEY_CAPABILITIES),
    "mcp-client-session": (
        McpClientSessionProvider,
        (MCP_LIST_TOOLS_CAPABILITY, MCP_CALL_TOOL_CAPABILITY),
    ),
    "memory": (MemoryProvider, MEMORY_CAPABILITIES),
    "multicloud": (MulticloudProvider, MULTICLOUD_CAPABILITIES),
    "platform-console": (PlatformConsoleProvider, PLATFORM_CONSOLE_CAPABILITIES),
    "resource-flow": (ResourceFlowProvider, RESOURCE_FLOW_CAPABILITIES),
    "sqlite": (SQLiteProvider, SQLITE_CAPABILITIES),
    "sregym": (SregymOntologyProvider, SREGYM_CAPABILITIES),
    "swegym": (SWEGymProvider, (SWEGYM_EVALUATE_CAPABILITY,)),
    "switchboard": (SwitchboardProvider, SWITCHBOARD_CAPABILITIES),
    "terraform-docker-apply": (TerraformDockerApplyProvider, TERRAFORM_DOCKER_APPLY_CAPABILITIES),
    "terraform-plan": (TerraformPlanProvider, TERRAFORM_PLAN_CAPABILITIES),
}

# Opt-in structured outcome predicates -- only providers with a real rg:outcomePredicateModule
# / rg:outcomePredicateExpr pair appear here. Empty for most providers by design.
_OUTCOME_PREDICATES: dict[str, Callable[[str, dict], bool]] = {
}


def builtin_provider_names() -> tuple[str, ...]:
    return tuple(sorted(_BUILTINS))


def builtin_capabilities(name: str) -> tuple[Any, ...]:
    try:
        return _BUILTINS[name][1]
    except KeyError as exc:
        raise ValueError(f"UNKNOWN_BUILTIN_PROVIDER:{name}") from exc


def create_builtin_provider(name: str) -> Any:
    try:
        provider_type = _BUILTINS[name][0]
    except KeyError as exc:
        raise ValueError(f"UNKNOWN_BUILTIN_PROVIDER:{name}") from exc
    return provider_type()


def describe_builtin_provider(name: str) -> dict[str, Any]:
    provider = create_builtin_provider(name)
    return {
        "name": name,
        "type": type(provider).__name__,
        "materialization_requires_authority": bool(
            getattr(provider, "materialization_requires_authority", False)
        ),
        "capabilities": [item.model_dump(mode="json") for item in builtin_capabilities(name)],
    }
