"""Built-in provider registry; semantic capability identity stays shared across transports.

GENERATED by ggen from ggen/gymact-registry-pack/ontology.ttl -- do not hand-edit. Adding a
new gym provider means adding an rg:RegisteredProvider individual to that ontology, not
editing this file's import block or `_BUILTINS` dict directly -- the generator cannot
"forget" a registration the way hand-editing two separate files (a new gym module plus this
dict) once did (see tests/test_registry_completeness_chicago.py's own docstring for the real
gap this closes: CloudTopologyProvider shipped without ever being registered here).
"""

from __future__ import annotations

from typing import Any

from gymact.gyms.chatman_state_gym import ChatmanStateProvider, CHATMAN_STATE_CAPABILITIES
from gymact.gyms.cloud_topology_gym import CloudTopologyProvider, CLOUD_TOPOLOGY_CAPABILITIES
from gymact.gyms.cloudsim import CloudSimProvider, CLOUDSIM_CAPABILITIES
from gymact.gyms.codebase import CodebaseProvider, CODEBASE_CAPABILITIES
from gymact.gyms.discovered import GenericDiscoveredProvider, DISCOVERED_RUN_CAPABILITY
from gymact.local_providers import FilesystemProvider, FILESYSTEM_CAPABILITIES
from gymact.gyms.ggen import GgenProvider, GGEN_CAPABILITIES
from gymact.gyms.ggen_legacy import GgenLegacyVerifierProvider, GGEN_LEGACY_CAPABILITIES
from gymact.local_providers import GitProvider, GIT_CAPABILITIES
from gymact.network_providers import HTTPJSONProvider, HTTP_JSON_CAPABILITIES
from gymact.gyms.k8s_resource_gym import K8sResourceProvider, K8S_RESOURCE_CAPABILITIES
from gymact.gyms.kubernetes_reconciliation import KubernetesReconciliationProvider, KUBERNETES_RECONCILIATION_CAPABILITIES
from gymact.gyms.lock_and_key import LockAndKeyProvider, LOCK_AND_KEY_CAPABILITIES
from gymact.gyms.mcp_client_session import McpClientSessionProvider, MCP_LIST_TOOLS_CAPABILITY, MCP_CALL_TOOL_CAPABILITY
from gymact.providers import MemoryProvider, MEMORY_CAPABILITIES
from gymact.gyms.multicloud import MulticloudProvider, CAPABILITY_REGISTRY as MULTICLOUD_CAPABILITIES
from gymact.gyms.resource_flow import ResourceFlowProvider, RESOURCE_FLOW_CAPABILITIES
from gymact.local_providers import SQLiteProvider, SQLITE_CAPABILITIES
from gymact.gyms.sregym import SregymVendorProvider, SREGYM_CAPABILITIES
from gymact.gyms.swegym import SWEGymProvider, SWEGYM_EVALUATE_CAPABILITY
from gymact.gyms.switchboard import SwitchboardProvider, SWITCHBOARD_CAPABILITIES
from gymact.gyms.terraform_docker_apply import TerraformDockerApplyProvider, TERRAFORM_DOCKER_APPLY_CAPABILITIES
from gymact.gyms.terraform_plan import TerraformPlanProvider, TERRAFORM_PLAN_CAPABILITIES

# NOT registered here (deliberately, not an oversight):
#   - gymact.gyms.browsergym.BrowserGymProvider: top-level `import browsergym.core` / `import gymnasium`, both gated behind the optional "gyms" extra -- importing this module with only the base install raises ImportError, so registering it would break a clean `import gymact.registry`.
#   - gymact.gyms.cube_container_counter.CubeContainerCounterProvider: top-level `from cube.infra_local import LocalInfraConfig` wrapped in try/except that re-raises ImportError, gated behind the optional "cube" extra with Docker.
#   - gymact.gyms.cube_counter.CubeCounterProvider: top-level `from counter_cube...` wrapped in try/except that re-raises ImportError, gated behind the optional "cube" extra (cube-standard/counter-cube, Python >=3.12 only).
#   - gymact.gyms.gymnasium_env.GymnasiumProvider: top-level `import gymnasium`, same optional "gyms" extra gate as browsergym.py above.
#   - gymact.gyms.inspect_evals.InspectEvalsProvider: top-level `from inspect_ai import ...`, gated behind the optional "gyms" extra (inspect-ai).
#   - gymact.gyms.vendor_benchmarks.VendorBenchmarkProvider: generic vendor-benchmark dispatch surface, not a single fixed-capability gym -- registered per-vendor benchmark target elsewhere, not as one flat builtin name here.

_BUILTINS = {
    "chatman-state": (ChatmanStateProvider, CHATMAN_STATE_CAPABILITIES),
    "cloud-topology": (CloudTopologyProvider, CLOUD_TOPOLOGY_CAPABILITIES),
    "cloudsim": (CloudSimProvider, CLOUDSIM_CAPABILITIES),
    "codebase": (CodebaseProvider, CODEBASE_CAPABILITIES),
    "discovered": (GenericDiscoveredProvider, (DISCOVERED_RUN_CAPABILITY,)),
    "filesystem": (FilesystemProvider, FILESYSTEM_CAPABILITIES),
    "ggen": (GgenProvider, GGEN_CAPABILITIES),
    "ggen-legacy": (GgenLegacyVerifierProvider, GGEN_LEGACY_CAPABILITIES),
    "git": (GitProvider, GIT_CAPABILITIES),
    "http-json": (HTTPJSONProvider, HTTP_JSON_CAPABILITIES),
    "k8s-resource": (K8sResourceProvider, K8S_RESOURCE_CAPABILITIES),
    "kubernetes-reconciliation": (KubernetesReconciliationProvider, KUBERNETES_RECONCILIATION_CAPABILITIES),
    "lock-and-key": (LockAndKeyProvider, LOCK_AND_KEY_CAPABILITIES),
    "mcp-client-session": (McpClientSessionProvider, (MCP_LIST_TOOLS_CAPABILITY, MCP_CALL_TOOL_CAPABILITY)),
    "memory": (MemoryProvider, MEMORY_CAPABILITIES),
    "multicloud": (MulticloudProvider, MULTICLOUD_CAPABILITIES),
    "resource-flow": (ResourceFlowProvider, RESOURCE_FLOW_CAPABILITIES),
    "sqlite": (SQLiteProvider, SQLITE_CAPABILITIES),
    "sregym": (SregymVendorProvider, SREGYM_CAPABILITIES),
    "swegym": (SWEGymProvider, (SWEGYM_EVALUATE_CAPABILITY,)),
    "switchboard": (SwitchboardProvider, SWITCHBOARD_CAPABILITIES),
    "terraform-docker-apply": (TerraformDockerApplyProvider, TERRAFORM_DOCKER_APPLY_CAPABILITIES),
    "terraform-plan": (TerraformPlanProvider, TERRAFORM_PLAN_CAPABILITIES),
}


def builtin_provider_names() -> tuple[str, ...]:
    return tuple(sorted(_BUILTINS))


def builtin_capabilities(name: str) -> tuple[Any, ...]:
    try:
        return _BUILTINS[name][1]
    except KeyError as exc:
        raise ValueError(f"UNKNOWN_BUILTIN_PROVIDER:{name}") from exc


def create_builtin_provider(name: str) -> Any:
    try:
        provider_type = _BUILTINS[name][0]
    except KeyError as exc:
        raise ValueError(f"UNKNOWN_BUILTIN_PROVIDER:{name}") from exc
    return provider_type()


def describe_builtin_provider(name: str) -> dict[str, Any]:
    provider = create_builtin_provider(name)
    return {
        "name": name,
        "type": type(provider).__name__,
        "materialization_requires_authority": bool(
            getattr(provider, "materialization_requires_authority", False)
        ),
        "capabilities": [item.model_dump(mode="json") for item in builtin_capabilities(name)],
    }
